[[content]]
section = "Technology"
source = "Recent content in Posts on Sullivan Scientific."
link = "https://www.sullivanscientific.com/2023/03/bookmarks-with-shaarli/"
pub_date = "Mon, 06 Mar 2023 08:05:28 -0500"
title = "Bookmarks With Shaarli"
bib_key = "harry"
content = "Shaarli - Managing bookmarks in a minimalist way TLDR; Here&rsquo;s a link: https://github.com/shaarli/Shaarli Here&rsquo;s a link to the demo site they host: https://demo.shaarli.org Being someone with ADHD, I have found few things more frustrating than figuring out where I tossed that article I want to review later, or bookmark for a system. Rarely do I log in to a browser - never on my work machines, and never on my phone."

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c79n1v4d203o"
pub_date = "Thu, 19 Sep 2024 19:44:31 GMT"
title = "Hezbollah leader says exploding device attacks crossed 'all red lines'"
bib_key = "harry"
content = 'Hassan Nasrallah calls the killing of 37 people by exploding pagers and radios an "unprecedented blow".'

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/19/nike-ceo-john-donahoe-is-out-replaced-by-elliott-hill.html"
pub_date = "Thu, 19 Sep 2024 22:23:35 GMT"
title = "Nike CEO John Donahoe is out, replaced by company veteran Elliott Hill"
bib_key = "harry"
content = "Nike CEO John Donahoe will retire from the company in October. He will be replaced by company veteran Elliott Hill."

[[content]]
section = "News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/9/19/israel-intensifies-air-raids-on-southern-lebanon-amid-escalation-fears?traffic_source=rss"
pub_date = "Thu, 19 Sep 2024 20:53:50 +0000"
title = "Israel intensifies air raids on southern Lebanon amid escalation fears"
bib_key = "harry"
content = "Israeli defence minister says Hezbollah to &#039;pay an increasing price&#039; as group promises retaliation over device attacks."
