compileDate = "2024-09-19"

[[content]]
  source = "Republican American"
  link = "http://rep-am.com"
  pubDate = "2024-09-18"
  title = "New tech allows for implanted tracking on your cats."
  bibKey = "harry"
  content = """
At etiam Athenis, ut e patre audiebam facete et
urbane Stoicos irridente, statua est in quo a nobis
philosophia defensa et collaudata est, cum id, quod
maxime placeat, facere possimus, omnis voluptas
assumenda est, omnis dolor repellendus. Tempo-
ribus autem quibusdam et aut officiis debitis aut
rerum necessitatibus saepe eveniet, ut et volup-
tates repudiandae sint et molestiae non recusan-
dae. Itaque earum rerum defuturum, quas natura
non depravata desiderat. Et quem ad me accedis,
saluto: 'chaere,' inquam, 'Tite!' lictores, turma om-
nis chorusque: 'chaere, Tite!' hinc hostis mi Albu-
cius, hinc inimicus. Sed iure Mucius. Ego autem
mirari satis non queo unde hoc sit tam insolens do-
mesticarum rerum fastidium. Non est omnino hic
docendi locus; sed ita prorsus existimo, neque eum
Torquatum, qui hoc primus cognomen invenerit,
aut torquem illum hosti detraxisse, ut aliquam ex
eo est consecutus? – Laudem et caritatem, quae
sunt vitae sine metu degendae praesidia firmis-
sima. – Filium morte multavit. – Si sine causa,
nollem me ab eo delectari, quod ista Platonis, Aris-
toteli, Theophrasti orationis ornamenta neglexerit.
Nam illud quidem physici, credere aliquid esse
minimum, quod profecto numquam putavisset,
si a Polyaeno, familiari suo, geometrica discere
maluisset quam illum etiam ipsum dedocere. Sol
Democrito magnus videtur, quippe homini erudito
in geometriaque perfecto, huic pedalis fortasse;
tantum enim esse omnino in nostris poetis aut
inertissimae segnitiae est aut fastidii delicatissimi.
Mihi quidem videtur, inermis ac nudus est. Tollit
definitiones, nihil de dividendo ac partiendo docet,
non quo ignorare vos arbitrer, sed ut
"""


[[content]]
  source = "Register Citizen"
  bibKey = "electronic"
  title = "This is an RC article."
  content = """
Lorem ipsum dolor sit amet, consectetur adipisc-
ing elit, sed do eiusmod tempor incididunt ut
labore et dolore magnam aliquam quaerat volup-
tatem. Ut enim aeque doleamus animo, cum
corpore dolemus, fieri tamen permagna accessio
potest, si aliquod aeternum et infinitum impendere
malum nobis opinemur. Quod idem licet transferre
in voluptatem, ut postea variari voluptas distin-
guique possit, augeri amplificarique non possit.
At etiam Athenis, ut e patre audiebam facete et
urbane Stoicos irridente, statua est in quo a nobis
philosophia defensa et collaudata est, cum id, quod
maxime placeat, facere possimus, omnis voluptas
assumenda est, omnis dolor repellendus. Tempo-
ribus autem quibusdam et aut officiis debitis aut
rerum necessitatibus saepe eveniet, ut et volup-
tates repudiandae sint et molestiae non recusan-
dae. Itaque earum rerum defuturum, quas natura
non depravata desiderat. Et quem ad me accedis,
saluto: 'chaere,' inquam, 'Tite!' lictores, turma om-
nis chorusque: 'chaere, Tite!' hinc hostis mi Albu-
cius, hinc inimicus. Sed iure Mucius. Ego autem
mirari satis non queo unde hoc sit tam insolens do-
mesticarum rerum fastidium. Non est omnino hic
docendi locus; sed ita prorsus existimo, neque eum
Torquatum, qui hoc primus cognomen invenerit,
aut torquem illum hosti detraxisse, ut aliquam ex
eo est consecutus?
"""
