[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cn8jg0x5xg8o"
pub_date = "Fri, 20 Sep 2024 15:53:45 GMT"
title = "Israel investigates after its soldiers filmed throwing bodies off roof"
bib_key = "key-5"
content = 'The IDF says the incident does not "conform" to its values, while Palestinian officials say it is a "crime".'

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cjr3255gpjgo"
pub_date = "Thu, 19 Sep 2024 23:12:45 GMT"
title = "Russia’s war dead tops 70,000 as volunteers face 'meat grinder'"
bib_key = "key-6"
content = "More than 70,000 Russian soldiers have died in Ukraine - volunteers now make up the highest number of deaths."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/20/indian-ed-tech-startup-physics-wallah-bags-2point8-billion-valuation-with-funding.html"
pub_date = "Fri, 20 Sep 2024 06:30:01 GMT"
title = "Indian ed-tech startup Physics Wallah bags $2.8 billion valuation amid sector troubles"
bib_key = "key-8"
content = "Physics Wallah CEO Alakh Pandey said the company would use the $210 million funding to expand its business and do acquisitions."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/20/american-airlines-credit-card-talks-to-pick-citigroup-over-barclays.html"
pub_date = "Fri, 20 Sep 2024 13:15:26 GMT"
title = "American Airlines in talks to pick Citigroup over rival bank Barclays for crucial credit card deal, sources say"
bib_key = "key-9"
content = "American has been working with banks and card networks on a new deal with the aim of consolidating its business with a single issuer, sources tell CNBC."

[[content]]
section = "Personal"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/9/20/israeli-forces-kill-dozens-across-gaza-as-tanks-advance-deeper-into-rafah?traffic_source=rss"
pub_date = "Fri, 20 Sep 2024 18:01:56 +0000"
title = "Israeli forces kill dozens across Gaza as tanks advance deeper into Rafah"
bib_key = "key-11"
content = "At least 13 people, including children, were killed in Israeli attacks on two homes in Rafah, medical sources say."

[[content]]
section = "Personal"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/9/20/more-than-70-killed-in-mali-attack-what-happened-why-it-matters?traffic_source=rss"
pub_date = "Fri, 20 Sep 2024 17:23:57 +0000"
title = "More than 70 killed in Mali attack: What happened, why it matters"
bib_key = "key-12"
content = "This is the first major attack on Bamako since 2015 when fighters targeted foreigners in a nightclub and hotel."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/world/middleeast/ibrahim-aqeel-hezbollah-commander-what-to-know.html"
pub_date = "Fri, 20 Sep 2024 16:36:55 +0000"
title = "Who Is Ibrahim Aqeel, the Hezbollah Commander Targeted by Israel?"
bib_key = "key-14"
content = "The senior leader, who survived multiple assassination attempts, has been sought by the United States for bombings in the 1980s. Here is a closer look."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/world/middleeast/israel-lebanon-attacks-hezbollah-war.html"
pub_date = "Fri, 20 Sep 2024 16:37:34 +0000"
title = "Israel’s Attacks on Hezbollah Have Intensified but Stop Short of All-Out War"
bib_key = "key-15"
content = "Israel is attempting a risky strategy, increasing the intensity of its attacks in an attempt to force Hezbollah to back down, while raising the chances of an aggressive response that devolves into a land war."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/world/middleeast/gaza-cease-fire-talks-hezbollah-lebanon.html"
pub_date = "Fri, 20 Sep 2024 11:22:08 +0000"
title = "With Focus Shifting to Lebanon, Some in Gaza Fear Cease-Fire Talks Will Be Sidelined"
bib_key = "key-16"
content = "Even as Israel signals that it is moving its focus to its northern border with Lebanon, there has been no pause to its bombardment in Gaza, where residents are facing another winter with little access to food or shelter."

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/life-arts/2024/09/20/cheshire-hosts-big-fat-combo-tonight/"
pub_date = "Fri, 20 Sep 2024 16:44:28 +0000"
title = "Cheshire hosts Big Fat Combo tonight"
bib_key = "key-18"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/09/20_fea_combo-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/09/20_fea_combo-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />Cheshire&#8217;s rockabilly favorites, Big Fat Combo, will play our outdoor stage along with The Sophisticatos featuring local troubadour Ken Safety. The concert begins with The Sophisticatos at 6 p.m., followed by Big Fat Combo at 7 p.m. If on-site parking is scarce, extended parking is available just over the Farmington Canal trail at the Municipal [&#8230;]'

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/localnews/2024/09/20/man-fatally-shot-by-officers-years-after-police-tried-to-steer-him-away-from-crime/"
pub_date = "Fri, 20 Sep 2024 15:02:35 +0000"
title = "Man fatally shot by officers years after police tried to steer him away from crime"
bib_key = "key-19"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2022/06/polic-blotter-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" loading="lazy" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2022/06/polic-blotter-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />ASSOCIATED PRESS WEST HAVEN — Connecticut police officers fatally shot a 36-year-old man whom authorities had tried to steer away from crime years ago. A state police sergeant and two New Haven police officers opened fire on the man late Thursday afternoon at a car wash in West Haven after they say he displayed a [&#8230;]'
