[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cjr3255gpjgo"
pub_date = "Thu, 19 Sep 2024 23:12:45 GMT"
title = "Russia’s war dead tops 70,000 as volunteers face 'meat grinder'"
bib_key = "key-5"
content = "More than 70,000 Russian soldiers have died in Ukraine - volunteers now make up the highest number of deaths."

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cn4yxe2xxzdo"
pub_date = "Fri, 20 Sep 2024 13:45:28 GMT"
title = "Harris says anyone breaking into her home is 'getting shot'"
bib_key = "key-6"
content = "The Democratic presidential nominee has discussed her gun ownership in a jokey exchange with Oprah Winfrey."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/20/eu-tariffs-on-chinese-evs-are-unlikely-to-dent-their-european-expansion.html"
pub_date = "Fri, 20 Sep 2024 09:48:43 GMT"
title = "Why EU tariffs are unlikely to dent Chinese EV makers' European expansion"
bib_key = "key-8"
content = "To make the European market unattractive for Chinese EV exports, tariffs have to be as high as 50%, according to research group Rhodium."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/20/american-airlines-credit-card-talks-to-pick-citigroup-over-barclays.html"
pub_date = "Fri, 20 Sep 2024 13:15:26 GMT"
title = "American Airlines in talks to pick Citigroup over rival bank Barclays for crucial credit card deal, sources say"
bib_key = "key-9"
content = "American has been working with banks and card networks on a new deal with the aim of consolidating its business with a single issuer, sources tell CNBC."

[[content]]
section = "Personal"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/newsfeed/2024/9/20/israeli-airstrikes-hit-densely-populated-beirut-neighbourhood?traffic_source=rss"
pub_date = "Fri, 20 Sep 2024 13:49:30 +0000"
title = "Israeli airstrikes hit densely populated Beirut neighbourhood"
bib_key = "key-11"
content = "Israeli airstrikes have hit the densely populated Dahiyeh neighbourhood of Lebanon’s capital Beirut."

[[content]]
section = "Personal"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/9/20/dozens-of-women-accuse-former-harrods-boss-mohamed-al-fayed-of-sexual-abuse?traffic_source=rss"
pub_date = "Fri, 20 Sep 2024 13:38:45 +0000"
title = "Dozens of women accuse former Harrods boss Mohamed al-Fayed of sexual abuse"
bib_key = "key-12"
content = "Harrods, now under Qatari ownership, issues apology for abuse of power when store was under al-Fayed’s control."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/podcasts/harris-trump-spending-hezbollah.html"
pub_date = "Fri, 20 Sep 2024 10:00:14 +0000"
title = "Harris Outspends Trump in Ad Battle, and Israel Bombards Hezbollah"
bib_key = "key-14"
content = "Plus, an iconic kitchen brand files for bankruptcy."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/us/politics/kamala-harris-trump-campaign-spending.html"
pub_date = "Fri, 20 Sep 2024 14:14:12 +0000"
title = "Kamala Harris Outspends Donald Trump by Tens of Millions Online"
bib_key = "key-15"
content = "The week of their debate, Kamala Harris outspent Donald Trump by 20 to 1 on Facebook and Instagram. It was just one sign of how uneven their online advertising battle has become."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/us/politics/kamala-harris-oprah-winfrey-event.html"
pub_date = "Fri, 20 Sep 2024 14:16:47 +0000"
title = "Harris Hits Core Campaign Themes in Emotional Forum With Oprah Winfrey"
bib_key = "key-16"
content = "Vice President Kamala Harris spoke off the cuff, as guests included a teenager shot at her school and the family of a woman in Georgia who died as a result of the state’s abortion ban."

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/localnews/2024/09/20/torrington-schools-closed-because-of-threat/"
pub_date = "Fri, 20 Sep 2024 14:19:25 +0000"
title = "Torrington schools closed because of threat"
bib_key = "key-18"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/07/torrington-icon-1-150x150.png" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/07/torrington-icon-1-150x150.png" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />Torrington schools closed because of threat Torrington schools closed Friday because of a threat the district received. Superintendent Michael Wilson posted on the district’s Facebook page the district was in contact with Torrington police and that while the threat was not determined to be caution. Multiple districts across the state decided to close Friday due [&#8230;]'

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/localnews/2024/09/20/connecticut-community-foundation-taps-chapman-frew-reynolds-balanda-as-trustees/"
pub_date = "Fri, 20 Sep 2024 13:47:33 +0000"
title = "Connecticut Community Foundation taps Chapman, Frew, Reynolds-Balanda as trustees"
bib_key = "key-19"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/09/28_new_032714js08-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" loading="lazy" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/09/28_new_032714js08-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />WATERBURY — Connecticut Community Foundation has announced the election of three community leaders to its board of trustees: Dr. Angela Chapman, Baba Frew and JoAnn Reynolds-Balanda. These new trustees will serve on a board that represents residents from across the foundation’s 21-municipality service area in Greater Waterbury and the Litchfield Hills. As stewards of the [&#8230;]'
