[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/10/14/india-canada-diplomatic-row-reignites-what-to-know-and-what-comes-next?traffic_source=rss"
pub_date = "Mon, 14 Oct 2024 23:15:40 +0000"
title = "India-Canada diplomatic row reignites: What to know and what comes next"
bib_key = "key-1"
content = """


EXPLAINER

*Canada accuses Indian government agents of being involved in ‘serious criminal activity’, a claim India rejects.*

Abetween India and Canada has reignited, with the two countries announcing the expulsion of diplomats amid accusations that Indian government agents were involved in activities that threaten the safety of Canadians.

The latest rowwhen India’s Ministry of External Affairs said it had received “diplomatic communication” from Canada indicating that Indian diplomats were being considered “persons of interest” in relation to an investigation in the North American country.

Relations between New Delhi and Ottawa hit new lows last year after the Canadian government said itbetween Indian government agents and the killing of a Sikh separatist leader, Hardeep Singh Nijjar, on Canada’s west coast.

New Delhi has denied any involvement in Nijjar’s killing, reiterating on Monday that it “strongly” rejected the “preposterous imputations” from Canada and would be withdrawing its diplomats and other officials from the country.

But hours later, the Canadianhad uncovered evidence that Indian agents were involved in activities that threaten public safety in Canada and it said it was expelling six Indian diplomats.

Here’s what we know about the deepening diplomatic row, what Canada and India have said about the matter, and what could happen next:
## What has Canada said?

* Canadian Prime Minister Justin Trudeau said on Monday that the federal Royal Canadian Mounted Police (RCMP) uncovered “clear and compelling evidence” that Indian government agents have engaged, and continue to engage, in activities that threaten public safety.
* “This includes clandestine information-gathering techniques, coercive behaviour targeting South Asian Canadians, and involvement in over a dozen threatening and violent acts, including murder,” Trudeau said during a news conference.
* Earlier in the day, the RCMP said it had found evidence of the involvement of Indian government agents “in serious criminal activity in Canada”, including links “to homicides and violent acts” and interference in democratic processes, among other things.
* “This evidence was presented directly to Government of India officials, urging their cooperation in stemming the violence and requesting our law enforcement agencies work together to address these issues,” the RCMP said in a.
* Canada’s foreign affairs department, Global Affairs Canada, then announced that six Indian diplomats and consular officials were being expelled from the country “in relation to a targeted campaign against Canadian citizens by agents linked to the Government of India”.
* India’s high commissioner to Canada was among those directed to leave.
* In a, Minister of Foreign Affairs Melanie Joly directly tied the Indian officials to Nijjar’s case: “The decision to expel these individuals was made with great consideration and only after the RCMP gathered ample, clear and concrete evidence which identified six individuals as persons of interest in,” she said.
Trudeau speaks to reporters in Ottawa, Canada, on October 14 [Blair Gable/Reuters]## What has India said?

* India’s Ministry of External Affairs vehemently rejected Canada’s allegations, saying in aon Monday that “on the pretext of an investigation, there is a deliberate strategy of smearing India for political gains”.
* The ministry also said that the Canadian government “has not shared a shred of evidence” with the Indian government, “despite many requests from our side”.
* Later, the ministry said it had summoned Canada’s charge d’affaires in India to inform him that “the baseless targeting of the Indian High Commissioner and other diplomats and officials in Canada was completely unacceptable”.
* “We have no faith in the current Canadian Government’s commitment to ensure their security. Therefore, the Government of India has decided to withdraw the High Commissioner and other targeted diplomats and officials,” it said, adding that New Delhi “reserves the right to take further steps” in response.
* Then – in a tit-for-tat move – the ministrythat it was expelling six Canadian diplomats from India, including the acting high commissioner, and was giving them until the end of the day on October 19 to leave India.
India’s Prime Minister Narendra Modi shakes hands with his Canadian counterpart Trudeau before the G20 Leaders’ Summit in New Delhi in 2023 [Evan Vucci/Pool via AFP]## How did India-Canada ties reach this point?

* Tensions between the two countries skyrocketed in September 2023 afterthat Canadian authorities were investigating “credible allegations of a potential link” between Indian government agents and the killing of Nijjar, a Canadian citizen.
* Nijjar was fatally shot on June 18, 2023, outside a Sikh temple where he served as president, in Surrey, British Columbia. He had been a leading advocate in what is known as, a Sikh campaign for a sovereign state in India’s Punjab region.
* While largely dormant inside India itself, Sikh separatism is largely viewed as a threat by the Indian government, which has urged Western nations to crack down on Khalistan movement leaders in the diaspora.
* India vehemently denied the allegations that it was involved in Nijjar’s killing, calling them “absurd”. It also accused Nijjar of being involved in “terrorism” – a claim rejected by his supporters.
* After Canada’s accusations were first made public, the two countriesand India also put a freeze on diplomatic services for Canadians.
* The tensions boiled over again in May 2024 when Canadian police said they had– all Indian nationals – accused of being involved in Nijjar’s killing. The RCMP said at the time that it was also “investigating if there are any ties to the government of India”.
* A fourth man, also an Indian national, wasin Nijjar’s killing later that month.
* New Delhi rejected the developments in Canada, with Minister of External Affairsthe country had a “political compulsion” to blame India.
## What comes next?

* It remains to be seen if India, as its foreign ministry said on Monday, would take “further steps” in response to Canada’s accusations – and if it does, what those steps could entail.
* Stephanie Carvin, a political analyst and professor at Carleton University in the Canadian capital of Ottawa, said the latest accusations by Canada were “very serious” and risked further hampering relations with India. That “puts Canada in a difficult position”, she said.
* “We’re in a time where we see countries around the world – the European Union, the United States, Australia … trying to develop their relations with India. This kind of puts us offside all of the other allies that we have,” she told Al Jazeera.
* Practically, Carvin also noted that Canada is home to a sizeable South Asian population and a large number of Indian students study in the country as well. “These Indian [nationals], they do need consular services, they need diplomatic representation in this country,” she said.
* Sikh Canadians told Al Jazeera over the past year that their community – which numbers about 770,000 people across Canada and makes up the largest Sikh diaspora outside India – had concerns about Indian state interference.
* The World Sikh Organization of Canada, a nonprofit that advocates for the community, said it welcomed the Canadian government’s announcement on Monday and demanded “the full prosecution of all individuals involved” in Nijjar’s killing, including Indian diplomats.
* “The Government of India’s ongoing foreign interference activities in Canada and its history of targeting Sikhs in this country is only now becoming known to the general public but has been the lived experience of Sikhs for the past four decades,”.

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c5y80p1yr9qo"
pub_date = "Mon, 14 Oct 2024 19:09:38 GMT"
title = "Lebanon says 21 killed in air strike in country’s north"
bib_key = "key-3"
content = """


At least 21 people have been killed and eight others injured in a rare Israeli air strike in northern Lebanon, the Lebanese health ministry says.

The strike hit a residential building in Aitou, a predominantly Christian village far from the areas where the Israeli military has carried out thousands of strikes targeting the armed Shia Islamist group Hezbollah.

Residents said a family recently displaced by the war had been living there.

The Israeli military did not immediately comment on the reports. But it came as Israeli Prime Minister Benjamin Netanyahu vowed to “continue to strike Hezbollah without mercy everywhere in Lebanon - including Beirut”.

“Everything is according to operational considerations. We have proven this recently and we will continue to prove it in the coming days as well,” he added.

He was speaking during a visit to a military base in northern Israel where a drone launched by the Iran-backed group killed four Israeli soldiers and wounded dozens on Sunday night.

The military said it was investigating how the drone evaded its sophisticated air defence systems and hit the Golani Brigade training facility near the town of Binyamina.

It was one of Hezbollah’s deadliest attacks on Israel in over a year of cross-border fighting sparked by the war in Gaza.

Hezbollah said it was a response to deadly Israeli attacks in Lebanon, which the country’s health ministry says has killed almost 1,700 people over the past month.

Most of the Israeli air strikes over the past week have struck in the majority Shia south and the Bekaa Valley in the east - areas where Hezbollah is strong.

Aitou, a Maronite Christian community located in the mountains near the north-western coastal city of Tripoli, was not a place which would have expected to be attacked.

“Oh mother Mary,” gasped one man as he walked through the devastation wrought on the village.

In the smoke and dust, bodies could be seen on the ground.

Residents said there was no warning, just a single, massive blast.

However, they also said several families displaced by the war in the south had recently moved to Aitou, and that the house which was hit had been rented out to new people just two weeks ago.

A Lebanese security source told AFP news agency that the building was “targeted shortly after a man had arrived in a car”.

The Lebanese health ministry said it was carrying out DNA tests to determine the identities of the remains recovered by first responders at the scene.

Also on Monday, the Israeli military said a strike in the southern Nabatieh area had killed the commander of the anti-tank unit of Hezbollah’s elite Radwan Force.

Hezbollah has not commented on the report.

The military also said it had struck Hezbollah launchers used to fire a number of rockets into central and northern Israel on Monday.

Most of the rockets were intercepted or fell in open areas, according to the military.

One woman was lightly injured by a barrage of 15 rockets that were fired towards the northern town of Karmiel.

Israeli police also said debris from an interception fell in the Holon area, south of Tel Aviv, without causing any injuries or damage.

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/videos/c4g5jxky8q0o"
pub_date = "Mon, 14 Oct 2024 21:10:07 GMT"
title = "‘I say bye to my kids, in case we don’t wake up’ – two Gazans film year under Israeli attack"
bib_key = "key-4"
content = """
Within days of Israel launching its war in Gaza last October, two Palestinians began filming their daily lives for the BBC. Aya fled to the south of the territory to find safety, Khalid chose to stay in the north. Between them, they document explosions, multiple evacuations, deaths and the trauma experienced by children caught up in the conflict.

Among the deeply human scenes, Khalid captures how his children's play has been affected by their exposure to the war while Aya films her emotional reaction to news, received from afar, that her home has been destroyed.

More than 42,000 Palestinians have been killed in Gaza as a result of Israeli military action, the Hamas-run health ministry says. It comes after about 1,200 people were killed in Hamas's 7 October attacks on Israel.

Aya and Khalid's stories are two of four featured in a new BBC World Service and Storyville documentary, Life and Death in Gaza.

. The film forms part of a group of programmes on BBC Two and BBC Four, and on iPlayer, marking one year on from 7 October and the war between Israel and Hamas. Another BBC Storyville,"""
