[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c079m9mxx1no"
pub_date = "Mon, 11 Nov 2024 13:19:19 GMT"
title = "Trump appoints UN ambassador Elise Stefanik and border tsar Tom Homan"
bib_key = "key-1"
content = '''


US President-elect Donald Trump has made two more key appointments ahead of his return to the White House in January.

Tom Homan, 62, will serve as Trump's "border tsar", having previously served as the returning president's acting director of Immigration and Customs Enforcement (Ice).

New York Congresswoman Elise Stefanik, 40, has also been made ambassador to the United Nations, the BBC's US partner CBS News has confirmed.

Meanwhile, Trump's Republican Party are edging closer to full control of the US Congress. They already have a majority in the Senate and need to win just a handful of seats to take the House of Representatives.

A party needs 218 seats to. The Republicans have 215 compared to the rival Democrats' 210, according to CBS.

Control of the House gives a party the power to initiate spending legislation and launch impeachment proceedings against officials.

* 
* 
* 
* 

A majority in the House, the lower chamber of Congress, alongside the Senate, the upper chamber, would give Trump a greater chance of getting his plans approved than if Democrats controlled one or both.

In the meantime, attention has switched to who he appoints to serve in his administration.

In a post on his Truth Social platform, Trump said Homan would be "in charge of our Nation’s Borders (“The Border Czar”), including, but not limited to, the Southern Border, the Northern Border, all Maritime, and Aviation Security".

He continued: "Likewise, Tom Homan will be in charge of all Deportation of Illegal Aliens back to their Country of Origin. Congratulations to Tom. I have no doubt he will do a fantastic, and long awaited for, job."

One of Trump's major campaign pledges was to deport immigrants who are in the US illegally.

A senior source close to Trump's transition told CBS News that Trump had picked Stefanik for ambassador to the UN, and Stefanik accepted the role.

"I am honoured to nominate Chairwoman Elise Stefanik to serve in my Cabinet as US Ambassador to the United Nations," Trump said shortly after in a statement to CBS News. "Elise is an incredibly strong, tough, and smart America First fighter."

She confirmed her acceptance of the role to the New York Post, saying she was "truly honoured".

"During my conversation with President Trump, I shared how deeply humbled I am to accept his nomination and that I look forward to earning the support of my colleagues in the United States Senate," she said.

Trump earlier appointed**Susie Wiles**as his chief of staff. In his election victory speech, Trump called her "the ice maiden" - a reference to her composure.

Other names in the running to join the administration are billionaire X owner**Elon Musk**, who played a key role in Trump's campaign, and**Robert F Kennedy Jr**- who ran his own presidential campaign before endorsing Trump.

There is speculation that Florida Senator**Rick Scott**could be in line to become Senate majority leader, having received the backing of Musk and others.

Trump has said**Nikki Haley**and**Mike Pompeo**- who both served in his first administration - will not be offered new positions.

Trump has confirmed that Homan will have a wide-ranging role overseeing border security and deportation policy - two of his main campaign issues.

Homan, a former police officer, also played an important role in Trump's first presidency as the acting director of Immigration and Customs Enforcement (Ice).

He resigned in 2018 but remained a proponent of Trump's hard-line approach. He supported separating migrant children from their parents as a means to deter illegal crossings, and has said politicians who support migrant sanctuary policies should be charged with crimes.

Homan is a visiting fellow at the Heritage Foundation - a conservative think-tank that published the Project 2025 document, which set out a "wish list" for a second Trump presidency. Trump has distanced himself from the organisation.

Stefanik became the youngest woman ever elected to Congress in 2014, then aged 30. She continues to represent New York’s 21st District.

After entering politics, the fourth-ranking House Republican initially positioned herself as a moderate and criticised Trump - but later became his loyal defender.

In his statement to the New York Post, Trump described her as "an incredibly strong, tough, and smart America First fighter".

The UN ambassador role is crucial to global cooperation and security, and Stefanik's nomination comes as conflicts continue to rage in Ukraine and the Middle East.

* UNITED KINGDOM:
* GLOBAL:
* AFRICA:
* ANALYSIS:
* IN PICS:
* IN FULL:

North America correspondent Anthony Zurcher makes sense of US politics in his twice weeklynewsletter. Readers in the UK can. Those outside the UK can.'''

[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/newsfeed/2024/11/11/saudi-crown-prince-urges-israel-to-end-wars-on-gaza-lebanon?traffic_source=rss"
pub_date = "Mon, 11 Nov 2024 14:32:31 +0000"
title = "Saudi Crown Prince urges Israel to end wars on Gaza, Lebanon"
bib_key = "key-3"
content = """
## Saudi Crown Prince urges Israel to end wars on Gaza, Lebanon

Saudi Crown Prince Mohammed bin Salman urged Israel to end its wars on Gaza and Lebanon. Speaking at a joint Arab League and Organisation of Islamic Cooperation summit, he added that Israel must also respect Iranian sovereignty.

Published On 11 Nov 2024

"""

[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/11/11/europe-braces-for-a-swift-and-brutal-transition-to-the-world-of-trump?traffic_source=rss"
pub_date = "Mon, 11 Nov 2024 14:24:54 +0000"
title = "Europe braces for a ‘swift and brutal transition’ to the world of Trump"
bib_key = "key-4"
content = """
European Union leaders took to social media on Wednesday morning to congratulate Donald J Trump on a sweeping presidential election victory in the United States, but few are likely to feel positive about the change of US leadership on security and trade, experts tell Al Jazeera.

“Trump has been very clear that Europeans need to ramp up their defence spending even further. He wants a three percent of GDP pledge and we can expect him to push this hard,” said Anna Wieslander, director for Northern Europe at the Atlantic Council.

NATO members pledged to raise defence spending to two percent of gross domestic product (GDP) after Russia invaded Crimea a decade ago. It has taken them until this year to achieve that, according to NATO, because many states did not act until Russia’s full-scale invasion of Ukraine in 2022.

“Europeans have long recognised the need to step up on security and defence, but this realisation has not been matched by resources or true political will,” Wieslander told Al Jazeera. “The systemic threat that Russia poses to European security makes this shift extremely urgent if American engagement decreases. The first thing Europe needs to do now is to take the lead in supporting Ukraine towards victory against Russia.”

Trump put pressure on Congress last year to delay $61bn in military aid to Ukraine, and has expressed scepticism about approving further aid, potentially saddling Europeans with that bill in addition to the 43.5 billion euros ($46.3bn) that the EU has already spent.

Bullying the Europeans into higher defence spending could be a double-edged sword.

Guy Verhofstadt, the federalist MEP who leads the Alliance of Liberals and Democrats for Europe, wrote on X: “The ‘free world’ will be led by a convicted felon and demagogue who doesn’t share our values but wants to destroy them. Liberal democracy is in peril. Is Europe prepared? No. Can it be and will we see real leadership we desperately need? Hopefully!”

French President Emmanuel Macron has been the standard-bearer for greater European strategic autonomy.

On Wednesday morning, he wrote on X, “I have just spoken with the [German] Chancellor Olaf Scholz. We will work towards a more united, stronger, more sovereign Europe in this new context.”

Within hours of that message, German Finance Minister Christian Lindner hadcoalition in a dispute over defence spending, and Scholz had declared a vote of confidence for January, followed by a possible early election in March.
## ‘It’s not going to be an instant wake-up call’

“Strategic autonomy will be hobbled by domestic conditions in France and Germany,” said Dimitar Bechev, director of the Dahrendorf Programme on Europe in a Changing World at the European Studies Centre at the University of Oxford.

Alongside Germany’s crumbling coalition, Macron has ruled through a minority government since parliamentary elections in July.

“There’s going to be some pain before that pain galvanises [the continent] into further European unity. It’s not going to be an instant wake-up call,” Catherine Fieschi, a fellow at the European University Institute’s Robert Schuman Centre, told Al Jazeera.

She attributed that to the German election and the European Parliament “auditioning commissioners, half of whom have been doing their job for the past five years, so it’s a colossal waste of time”.

“In January as we know, it’s going to be a swift and brutal transition of [US] power,” she said. “We’re going to see a dip, some panic, some chaos, some uncertainty. In the end, given the brutality of what’s coming from the Trump White House, we’re going to see more cohesion in Europe than what we’ve seen for the past years.”

She added, “I think we’re finally maybe going to see thethat’s been promised for years actually taking shape”.

Scholz announced a Zeitenwende, or epochal change, soon after Russia’s 2022 full-scale invasion of Ukraine, consisting in part of a defence-spending hike of 100 billion euros ($106bn). It has taken him until 2024 to actually bring defence spending to two percent of GDP.

Europe will also be up against opposition to autonomy from Trump, says Wieslander.

“He does not want the European defence market to become autonomous, which is a prerequisite for European strategic autonomy. Rather, we saw during the previous Trump administration that he pushed Europeans to buy more American defence material. Neither has he expressed any wish for the Europeans to develop their own nuclear deterrence, another necessary condition for European strategic autonomy.”

European Parliament research recently showed that after 2022, 78 percent of EU members’ procurement budgets were awarded outside the EU, including 63 percent in the US – an even higher proportion than before the Ukraine war.

And despite the fact that the EU is fast transitioning to autonomous, renewable energy, it still bleeds at least half a trillion dollars a year importing fossil fuels, partly from the US.

Yet Europe contains two nuclear powers, with permanent seats on the United Nations Security Council. It could act autonomously if it wanted to.

If they react to outside pressures in the right way, European leaders can still achieve autonomy, says Constantinos Filis, a professor of history at the American College of Greece. “It could turn out that Trump and Putin actually mould the new shape of Europe,” he said.
## Trump’s looming trade war

Trump’s promise to slap a 10 percent tariff on all imports, including those from Europe, and a 60 percenton all Chinese imports, will be a greater concern, believes Fieschi.

“We’re in for a double whammy. On the one hand, [there’s] a security guarantee dependent on Europe’s toeing the line on China. We’re in line to see very transparent and aggressive measures to force key industries to manufacture in the US,” she said, with tariffs as a stick complementing the carrot of subsidies under US President Joe Biden’s Inflation Reduction Act.

Bechev agrees on expectations of “protracted negotiations on trade, with the spectre of an all-out trade war looming large in the backdrop”.

It is this assault on European agriculture, manufacturing and trade that may unite European mainstream and anti-systemic parties, in the end, believes Fieschi. “[Jordan]and [Marine] Le Pen have been going out of their way to say, ‘We want to protect our Europe,” she said of the leaders of the far-right National Rally party in France.

“They’re sounding exactly like Macron on strategic autonomy.”

That fear of a complete colonisation of the European economy by the US will be further reinforced, she predicts.

“We’re going to see someone who is really prepared to break the rules completely, not just rewrite them,” said Fieschi.

“What that will mean for Europe is how much time are we going to spend dragging disputes in front of the World Trade Organization, and European Court of Justice. We’re going to drown in our own regulations and self-righteousness with someone who really may not care at all.”"""
