[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/10/16/italy-sends-first-asylum-seekers-to-albania-under-controversial-deal?traffic_source=rss"
pub_date = "Wed, 16 Oct 2024 13:36:16 +0000"
title = "Italy sends first asylum seekers to Albania under controversial deal"
bib_key = "key-1"
content = """


*Rome boasts of deal processing asylum seekers outside EU. Critics complain of ‘cruel experiment’ that undermines human rights.*

An Italian navy ship has docked in Albania to deliver refugees and migrants, the first such mission under a controversial deal between the two countries that sends asylum seekers outside the European Union while their claims are processed.

The ship, carrying 16 men who were picked up in Italian waters, arrived at Shengjin port on Wednesday. The arrangement has been heralded by Italy’s right-wing government as unprecedented and eyed by other, but rights groups have slammed it as undermining human rights.

Ten men from Bangladesh and six from Egypt disembarked from the ship. They are the first arrivals under the deal, which wasin November.

The naval ship Libra left the port of Lampedusa on Monday. The refugees were rescued at sea after departing from Libya last week, according to officials.

On arrival in Albania, they were escorted towards the gates of a processing centre a few metres from the vessel. Their cases will be heard at a nearby airbase in Gjader, which can hold 3,000 people.

Italy has opened two centres in Albania, where it plans to process up to 36,000 asylum seekers per year. The centres will be operated under Italian law with Italian security and staff and judges hearing cases by video from Rome.

According to the deal, agreed for an initial five years by Italian Prime Minister Giorgia Meloni and her Albanian counterpart, Edi Rama, people will be screened initially on board the ships that rescue them before being sent to Albania for further screening.

Refugees intercepted in Italian waters who are deemed the most vulnerable, including women and children, will be taken to Italy.

The deal is being implemented while other EU states are seeking to adoptamid pressure from the, which made significant headway in EU elections in the summer.

Albania has said it will work exclusively with Italy.
## ‘Cruel experiment’

A small group of activists gathered at the entrance of the port to protest the arrival of the refugees, holding a banner saying, “The European dream ends here.”

Rights groups have questioned whether the deal complies with international law.

Amnesty International has called the centres a “cruel experiment [that] is a stain on the Italian government”. Doctors Without Borders said the new strategy “raises serious human rights concerns”.

Meloni brushed aside the criticism in comments on Tuesday.

“It is a new, courageous,but one that perfectly reflects the European spirit and has everything it takes to be followed also with other non-EU nations,” she said.

The first mission under the deal comes before an EU summit in Brussels this week, at which migration is set to be a major topic.

In a letter to member states before the talks, European Commission chief Ursula von der Leyen said the bloc would “be able to draw lessons from this experience in practice”.
A group of rights activists protests after the first group of refugees intercepted in Italian waters arrived at Shengjin, Albania, on October 16, 2024 [Adnan Beci/AFP]## ‘Part of the problem’

Critics have declared that given the high cost of the operation, the limited capacity of the processing centres and the fact that Italy is unlikely to be able to eventually deport most of the refugees, the deal won’t have the desired effect of “deterrence”.

Migration researcher Matteo Villa of Datalab Europe said: “The more migrants decide to undertake the journey, the higher the probability of being brought to Italy because the capacity of the Albanian centre is fixed.”

“No matter how you look at it, not only will the idea of opening a centre in Albania not be part of the solution, but it will become part of the problem,” he argued.

The number of people reaching Italy along the central Mediterranean migration route from North Africa fell by 61 percent in the first nine months of 2024 compared with the same period of 2023.

According to the Italian Ministry of the Interior, as of Tuesday, 54,129 refugees had arrived in Italy by sea so far this year, compared with 138,947 by the same date last year.

The two centres in Albania will cost Italy 670 million euros ($730m) over five years.

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cd0z8gg5v14o"
pub_date = "Wed, 16 Oct 2024 11:24:29 GMT"
title = "Zelensky presents 'victory plan' to Ukrainian parliament"
bib_key = "key-3"
content = '''


Ukrainian President Volodymyr Zelensky has presented MPs with a long-awaited "victory plan" that aims to strengthen his country's position enough to end the war with Russia.

Zelensky told parliament in Kyiv that the plan could finish the war - which began with Russia's full-scale invasion of Ukraine in February 2022 - no later than next year.

Key elements include a formal invitation to join Nato, the lifting by allies of restrictions on long-range strikes on Russia, a refusal to trade Ukraine’s territories and sovereignty, and the continuation of the incursion into the Kursk region of Russia.

The Kremlin dismissed the plan with a spokesman saying Kyiv needed to "sober up".

Addressing MPs, Zelensky also criticised China, Iran and North Korea for their backing of Russia, and described them as a "coalition of criminals".

He said he would present the victory plan at an EU summit on Thursday.

"We are at war with Russia on the battlefield, in international relations, in the economy, in the information sphere, and in people's hearts," Zelensky told parliament.

The plan outlined by Zelensky consists of five key points:

* Inviting Ukraine to join Nato
* The strengthening of Ukrainian defence against Russian forces, including getting permission from allies to use their long-range weapons on Russian territory, and the continuation of Ukraine's military operations on Russian territory to avoid creation of the "buffer zones" in Ukraine
* Containment of Russia via a non-nuclear strategic deterrent package deployed on Ukrainian soil
* Joint protection by the US and the EU of Ukraine's critical natural resources and joint use of their economic potential
* For the post-war period only: replacing some US troops stationed across Europe with Ukrainian troops

Three "addendums" remain secret and will only be shared with Ukraine's partners, Zelensky said.

The plan was presented to US President Joe Biden, as well as presidential candidates Kamala Harris and Donald Trump, back in September.

Key allies such as Britain, France, Italy and Germany have also reportedly been shown the plan.

However Zelensky's conditions for peace are increasingly at odds with the situation which surrounds him.

In front of MPs he acknowledged the growing fatigue in his country. His own tiredness was etched across his face as he said that "victory has become for some an uncomfortable word and it’s not easy to achieve."

National morale has gradually been crumbling under the weight of a mounting death toll, a controversial mobilisation law and never-ending Russian assaults on Ukrainian territory.

It’s increasingly thought any peace deal would have to involve Ukraine conceding territory in exchange for security guarantees.

However, there was no hint of a compromise to bring the end of the war closer. Instead, Zelensky doubled down on wanting to force Russia to negotiate and to not cede Ukraine’s territory, through the strengthening of his own military.

He also claimed his extensive plan could be implemented with the agreement of his allies, and not Russia.

In public, Zelensky evidently still sees this war as existential, and warned of Russian President Vladimir Putin continuing to strengthen his position.

He also seemed to frame his vision as an investment opportunity for Western allies in terms of natural resources and economic potential.

The Ukrainian president wants his exhausted troops to keep fighting.

But with his army so reliant on Western aid, his "victory plan" will need the approval of the next US president.

Immediately after Zelensky finished speaking, the Kremlin rubbished his "ephemeral peace plan," saying Kyiv needed to "sober up".

The only way the war would end was Ukraine to "realise the futility of the policy it is pursuing," Kremlin spokesman Dmitry Peskov said.

'''

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c9wk0e8zey2o"
pub_date = "Wed, 16 Oct 2024 04:36:27 GMT"
title = "US gives Israel 30 days to boost Gaza aid or risk cut to military support"
bib_key = "key-4"
content = '''


Reuters

The US says the 1.7 million Palestinians crowded into the al-Mawasi area are at “high risk of lethal contagion”

The US has written to Israel, giving it 30 days to boost humanitarian aid access in Gaza or risk having some US military assistance cut off.

The letter, sent on Sunday, amounts to the strongest known written warning from the US to its ally and comes amid a new Israeli offensive in northern Gaza that has reportedly caused a large number of civilian casualties.

It says the US has deep concerns about the deteriorating humanitarian situation, adding that Israel denied or impeded nearly 90% of humanitarian movements between the north and south last month.

Israel is reviewing the letter, an Israeli official was reported as saying, adding the country "takes this matter seriously" and intends to "address the concerns raised" with US counterparts.

Israel has previously said it is targeting Hamas operatives in the north and not stopping the entry of humanitarian aid.

On Monday, the Israeli military body responsible for managing crossings into Gaza, Cogat, said 30 lorries carrying aid from the World Food Programme had entered northern Gaza through the Erez crossing.

That ended a two-week period during which the UN said no food aid was delivered to the north, and supplies essential for survival were running out for the 400,000 Palestinians there.

A UN official has said that Gaza is in a state of "constant peak emergency".

Antoine Renard, head of the World Food Programme (WFP) in the occupied Palestinian territories, told the AFP news agency people in the north of the territory were "relying solely on assistance" with practically no access to fresh food other than that provided by UN agencies.

The US is by far the biggest supplier of arms to Israel, and the Israeli military has relied heavily on US-supplied aircraft, guided bombs, missiles and shells to fight the war against Hamas in Gaza over the past year.

The US letter to the Israeli government - the contents of which have now been confirmed by the state department - was first reported by the Axios website. It is signed by Secretary of State Antony Blinken and Defence Secretary Lloyd Austin.

"We are now writing to underscore the US government’s deep concern over the deteriorating humanitarian situation in Gaza, and seek urgent and sustained actions by your government this month to reverse this trajectory," it says.

It states that Israeli evacuation orders have forced 1.7 million people into the narrow, coastal al-Mawasi area where they are at “high risk of lethal contagion” due to extreme overcrowding, and that humanitarian organisations report that their survival needs cannot be met.

"We are particularly concerned that recent actions by the Israeli government - including halting commercial imports, denying or impeding nearly 90% of humanitarian movements between northern and southern Gaza in September, continuing burdensome and excessive dual-use restrictions, and instituting new vetting and onerous liability and customs requirements for humanitarian staff and shipments - together with increased lawlessness and looting - are contributing to an accelerated deterioration in the conditions in Gaza," it adds.

The letter says Israel "must, starting now and within 30 days" act on a series of concrete measures to boost aid supplies, adding that failure may “have implications for US policy”.

It cites US laws which can prohibit military assistance to countries that impede delivery of US humanitarian aid.

It says Israel must "surge all forms of humanitarian assistance throughout Gaza" before winter, including by enabling a minimum of 350 lorries a day to enter through all four major crossings and a new fifth crossing, as well as allowing people in al-Mawasi to move inland.

It also calls on Israel to end the "isolation of northern Gaza" by reaffirming that there will be "no Israeli government policy of forced evacuation of civilians" from north to south.

At a news conference in Washington on Tuesday, US state department spokesman Matthew Miller told reporters that the letter was "a private diplomatic communication that we did not intend to make public".

"Secretary [Blinken] along with Secretary Austin thought it was appropriate to make clear to the government of Israel that there are changes they need to make again to see the level of assistance making it into Gaza comes back up," he said.

Mr Miller declined to speculate on what consequences there might be for Israel if it did not boost humanitarian aid access.

But he noted: "Recipients of US military assistance do not arbitrarily deny or impede provisioning of US humanitarian assistance. That’s just the law and we of course will follow the law. But our hope is that Israel will make the changes that we have outlined."

He also said the 30-day time limit was not linked to the upcoming US presidential election on 5 November, saying it was "appropriate to give them time to work through the different issues".

Israel has previously insisted there are no limits to the amount of aid or humanitarian assistance that can be delivered into and across Gaza, and blames UN agencies for failing to distribute supplies. It also accuses Hamas of stealing aid, which the group denies.

Before Israel’s ground offensive in the southern Gaza city of Rafah in May, President Joe Biden suspended a single consignment of 2,000 and 500lb bombs for the first time as he tried to dissuade it from an all-out assault.

But the president immediately faced a backlash from Republicans in Washington and from Israeli Prime Minister Benjamin Netanyahu, who appeared to compare it to an "arms embargo". The suspension was partially lifted in July and has not been repeated.

AFP

Jabalia has come under heavy bombardment since the Israeli military launched a new ground offensive there 10 days ago

Earlier on Tuesday, the International Committee of the Red Cross (ICRC) warned that families in northern Gaza were "facing unimaginable fear, loss of loved ones, confusion, and exhaustion" because of the Israeli offensive that began 10 days ago.

The Israeli military says it has sent tanks and troops back into the town of Jabalia and its urban refugee camp for a third time to root out Hamas fighters who have regrouped there.

It has ordered residents of Jabalia, as well as neighbouring Beit Lahia and Beit Hanoun, to evacuate to the al-Mawasi "humanitarian area".

The UN says about 50,000 people have fled to Gaza City and other parts of the north. But for many it is unsafe to leave their homes or they are unable to leave because they are sick or disabled.

Khalid,, said in a voice note that he and his family had been living in fear for a week.

"We were told to go to the south, but we couldn’t because the Israeli army has surrounded the area, either with dirt barricades or using quadcopter drones. We can’t move, it’s too difficult."

"At the same time, because of the intense bombing we’re living in constant terror. My daughter has become sick and she has a fever. Her entire body is shaking in fear because of the sound of the bombings and I don’t know what to do with her. I can’t even take her to the hospital," he added.

Gaza’s Hamas-run Civil Defence agency said its first responders had recovered the bodies of 42 people killed by Israeli air and artillery strikes in Jabalia and neighbouring areas on Tuesday.

They reportedly included 11 members of the same family, nearly all of them women and children, whose home was destroyed in an air strike overnight.

The Israeli military said on Tuesday that its troops had killed “dozens of terrorists” in the Jabalia area over the previous day.

On Monday,, echoing widespread Palestinian concerns.

The controversial plan calls for the forcible transfer of all civilians in the north followed by a siege of the Hamas fighters remaining there to force their surrender and the release of Israeli hostages.

The Israeli military denies it is being implemented, saying it is only “getting civilians out of harm's way”.

Israel launched a campaign to destroy Hamas in response to the group's unprecedented attack on southern Israel on 7 October 2023, in which about 1,200 people were killed and 251 others were taken hostage.

More than 42,340 people have been killed in Gaza since then, according to the territory's Hamas-run health ministry.

'''

[[content]]
section = "Science"
source = "math updates on the arXiv.org e-print archive."
link = "https://arxiv.org/abs/2410.10822"
pub_date = "Wed, 16 Oct 2024 00:00:00 -0400"
title = "Maximal subrings of certain non-commutative rings"
bib_key = "key-6"
content = '''


> Abstract:The existence of maximal subrings in certain non-commutative rings, especially in rings which are integral over their centers, are investigated. We prove that if a ring $T$ is integral over its center, then either $T$ has a maximal subring or $T/J(T)$ is a commutative Hilbert ring with $|Max(T)|\\leq 2^{\\aleph\_0}$ and $|T/J(T)|\\leq 2^{2^{\\aleph\_0}}$. We observe that if $T$ is an algebraic $K$-algebra over a field $K$, then either $T$ has a maximal subring or $U(T)$ is integral over the prime subring of $T$. If $T$ is a left Artinian ring which is integral over its center, then we prove that either $T$ has a maximal subring or $T$ is countable and is integral over its prime subring. We see that if $T$ is a left Noetherian ring which is integral over its center, then either $T$ has a maximal subring or $|T|\\leq 2^{\\aleph\_0}$. We prove that if $T$ is a domain which is integral over its center $C$ and $J(C)=0$, then either $T$ has a maximal subring or $T$ is an integral domain. If $T$ is a reduced ring which is integral over its center and the center of $T$ is a Hilbert ring, then we show that either $T$ has a maximal subring or $T$ is commutative. We see that if a ring $T$ is integral over its center and $R$ is a subring of $T$ with $J(T)\\cap R\\subseteq J(R)$, then either $T$ has a maximal subring or $J(R)=J(T)\\cap R$ and $U(R)=U(T)\\cap R$. Finally, we prove that if $T$ is direct product of an infinite family of rings $\\{T\_i\\}\_{i\\in I}$ and each $T\_i$ is integral over its center, then $T$ has a maximal subrings.

## Submission history

From: Alborz Azarang []
**[v1]**Thu, 12 Sep 2024 14:43:46 UTC (19 KB)

'''
