[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/10/14/frances-marine-le-pen-pleads-innocence-at-eu-embezzlement-trial?traffic_source=rss"
pub_date = "Mon, 14 Oct 2024 19:05:17 +0000"
title = "France’s Marine Le Pen questioned in court at EU embezzlement trial"
bib_key = "key-1"
content = """


*Marine Le Pen and her RN party have been accused of using European Parliament money to pay staff in France between 2004 and 2016.*

French far-right leader Marine Le Pen has strongly denied committing any wrongdoing at a Paris court as she and her National Rally (RN) party stand trial over the suspected embezzlement of European Parliament funds.

The nine-week trial is a critical juncture for Le Pen, expected to be a strong contender in France’s next presidential election in 2027. A guilty verdict could significantly affect her political career and aspirations.

Le Pen, 56, took to the stand on Monday in the first of three expected days of testimony in the trial, which comes almost a decade after initial investigations began.

Le Pen, the RN itself, and 24 others – including party officials, employees, and former lawmakers – have all been accused of using European Parliament money to pay staff in France.

The party leader and her co-defendants have denied the charges, saying the money was used legitimately.

In court, Le Pen argued that she believed a European Parliament member’s role was as much to push their party’s politics in France as it was to work on legislation in Brussels.

“I’m telling you very clearly: I absolutely don’t feel I have committed the slightest irregularity, the slightest illegal move,” she said.

She detailed her vision of the role that MEPs play, including various examples such as meeting with voters and attending major events.

“The aide works for his MEP and [therefore] can work for his MEP for the benefit of the party,” she explained.

“I believe it’s a mistake from the European Parliament not to perceive it this way,” she added.

The judge presiding over the case said she was unsatisfied with Le Pen’s answers.
## ‘Fake jobs’

The European Parliament has estimated the damage from the alleged crimes to be 3.5 million euros ($3.8m).

The alleged fake jobs system that triggered the trial was first flagged in 2015 and covers parliamentary assistant contracts between 2004 and 2016.

Prosecutors say the assistants worked solely for the party outside parliament. Many could not describe their day-to-day work, and some never met their supposed MEP boss.

A bodyguard, a secretary, Le Pen’s chief of staff and a graphic designer were all allegedly hired under false pretences.

If Le Pen and her co-defendants are found guilty, they could face up to 10 years in prison and fines of up to one million euros ($1.1m) each.

A guilty verdict could also result in penalties including a loss of civil rights or ineligibility to run for office, which would affect Le Pen’s goal of becoming France’s president in the 2027 election.

The trial is scheduled to last until November 27.

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c5y80p1yr9qo"
pub_date = "Mon, 14 Oct 2024 19:09:38 GMT"
title = "Lebanon says 21 killed in air strike in country’s north"
bib_key = "key-3"
content = """


At least 21 people have been killed and eight others injured in a rare Israeli air strike in northern Lebanon, the Lebanese health ministry says.

The strike hit a residential building in Aitou, a predominantly Christian village far from the areas where the Israeli military has carried out thousands of strikes targeting the armed Shia Islamist group Hezbollah.

Residents said a family recently displaced by the war had been living there.

The Israeli military did not immediately comment on the reports. But it came as Israeli Prime Minister Benjamin Netanyahu vowed to “continue to strike Hezbollah without mercy everywhere in Lebanon - including Beirut”.

“Everything is according to operational considerations. We have proven this recently and we will continue to prove it in the coming days as well,” he added.

He was speaking during a visit to a military base in northern Israel where a drone launched by the Iran-backed group killed four Israeli soldiers and wounded dozens on Sunday night.

The military said it was investigating how the drone evaded its sophisticated air defence systems and hit the Golani Brigade training facility near the town of Binyamina.

It was one of Hezbollah’s deadliest attacks on Israel in over a year of cross-border fighting sparked by the war in Gaza.

Hezbollah said it was a response to deadly Israeli attacks in Lebanon, which the country’s health ministry says has killed almost 1,700 people over the past month.

Most of the Israeli air strikes over the past week have struck in the majority Shia south and the Bekaa Valley in the east - areas where Hezbollah is strong.

Aitou, a Maronite Christian community located in the mountains near the north-western coastal city of Tripoli, was not a place which would have expected to be attacked.

“Oh mother Mary,” gasped one man as he walked through the devastation wrought on the village.

In the smoke and dust, bodies could be seen on the ground.

Residents said there was no warning, just a single, massive blast.

However, they also said several families displaced by the war in the south had recently moved to Aitou, and that the house which was hit had been rented out to new people just two weeks ago.

A Lebanese security source told AFP news agency that the building was “targeted shortly after a man had arrived in a car”.

The Lebanese health ministry said it was carrying out DNA tests to determine the identities of the remains recovered by first responders at the scene.

Also on Monday, the Israeli military said a strike in the southern Nabatieh area had killed the commander of the anti-tank unit of Hezbollah’s elite Radwan Force.

Hezbollah has not commented on the report.

The military also said it had struck Hezbollah launchers used to fire a number of rockets into central and northern Israel on Monday.

Most of the rockets were intercepted or fell in open areas, according to the military.

One woman was lightly injured by a barrage of 15 rockets that were fired towards the northern town of Karmiel.

Israeli police also said debris from an interception fell in the Holon area, south of Tel Aviv, without causing any injuries or damage.

"""
