[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c80rkv0k4j8o"
pub_date = "Thu, 26 Sep 2024 16:37:45 GMT"
title = "Republican anger clouds Zelensky-Biden 'victory plan' meeting"
bib_key = "key-1"
content = '''


Volodymyr Zelensky was due to meet the US president at the White House on Thursday, as a row with Donald Trump and the broader Republican party escalated.

Republicans in Congress reacted angrily to the Ukrainian president's decision to visit an arms factory in Biden's hometown of Scranton with several top Democrats, and it now appears Zelensky will not meet Trump as had been expected.

Zelensky will pitch a "victory plan" to Joe Biden and Vice-President Kamala Harris which he says will help force Russia to find a diplomatic end to the war.

Earlier, Biden announced a $7.9bn (£5.9bn) package of military assistance to Ukraine.

Zelensky's visit with several top Democrats to an ammunition factory in the key swing state of Pennsylvania has widely angered leading Republicans, who labelled it a partisan campaign event.

In a public letter, speaker of the US House Mike Johnson said the visit was "designed to help Democrats" and claimed it amounted to "election interference".

He also demanded that Ukraine fire its ambassador to Washington who helped arrange the visit.

The Republican-led House Oversight Committee has also announced it would investigate whether Zelensky's trip was an attempt to use a foreign leader to benefit Vice-President Kamala Harris's campaign.

Her Republican rival for the presidency, Donald Trump, mocked Zelensky at a campaign event as the "greatest salesman on Earth" and accused him of refusing to "make a deal" with Moscow.

During an earlier rally on Tuesday, Trump also praised Russia's military capabilities, saying: "They beat Hitler, they beat Napoleon - that’s what they do, they fight."

The two men have long had a fractious relationship. In 2019, Trump was impeached by the US House over accusations that he pressured Ukraine's leader to dig up damaging information on a political rival.

The row clouded a week in which Zelensky has twice addressed the United Nations, ramping up efforts to persuade the US and other allies to boost support more than two and a half years into Russia's full-scale invasion.

His so-called victory plan has so far been kept under wraps, although he has described it as a "bridge" towards stopping the war that has to be agreed and put into action in the next three months.

Zelensky also needs US backing to fire Western-made long-range missiles deep into Russian territory, which Biden has so far blocked.

On the eve of the White House meeting, Russia's Vladimir Putin announced a plan to revise Moscow's nuclear doctrine, to enable Russia to use nuclear weapons against non-nuclear states if they are supported by nuclear states.

Putin's spokesperson later clarified that it was meant as a "specific signal" to the West.

* 

Hours before his meeting with Zelensky, President Biden announced a "surge in security assistance for Ukraine and a series of additional actions to help Ukraine win this war".

The aid, part of a $61bn package that passed Congress in April, will be approved through presidential drawdown authority and will pull from existing Pentagon supplies to deliver the arms more quickly.

Congressional Republicans blocked the package for months earlier this year, before ultimately relenting and passing the legislation. The delay caused arms supplies to Ukraine to dry up for several months.

Responding to the aid package, Zelensky thanked the US - Ukraine's largest foreign donor - and said he was "grateful to Joe Biden, US Congress and its both parties".

Russia's missile and drone attacks on Ukraine have continued while Zelensky is in the US.

The Sumy, Odesa and Kyiv regions were all attacked overnight, leaving one woman dead in Odesa and numerous reported injuries.

In the capital, air raid sirens and explosions from Ukraine's air defences continued for hours.

* SIMPLE GUIDE:
* EXPLAINER:
* FACT CHECK:

North America correspondent Anthony Zurcher makes sense of the race for the White House in his weekly US Election Unspun newsletter.

Readers in the UK. Those outside the UK

'''

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/czd13mezz7mo"
pub_date = "Thu, 26 Sep 2024 15:04:56 GMT"
title = "Florida braces for hurricane to bring 20-foot storm surge"
bib_key = "key-2"
content = '''


Helene to make landfall in Florida as category 4 hurricane

The state of Florida has issued a number of mandatory evacuation orders as Hurricane Helene strengthened over the Gulf of Mexico.

As of Thursday morning, the storm had grown into a category 2 hurricane and is expected to make landfall on Florida’s Big Bend later in the evening.

Officials have urged people to heed evacuation orders, warning that the storm will bring “life-threatening” weather to the region with destructive winds and significant storm surge.

It is expected to make landfall as a category 4 hurricane south of Tallahassee, a city that has not seen a storm of this magnitude in recent memory.

Hurricane Helene has been described as “catastrophic” and “unsurvivable” by officials, who warned that it will bring with it a storm surge of up to 20 ft above ground level in some areas of the Big Bend.

“This forecast, if realised, is a nightmare surge scenario for Apalachee Bay,” the National Weather Service office in Tallahassee warned in a bulletin.

Michael Brennan, the director of the National Hurricane Centre (NHC), said on Thursday that residents under evacuation orders still have time to get out, but added that “conditions are going to deteriorate quickly.”

Power outages, tree damage and powerful winds that could tear roofs off of structures are expected, Mr Brennan said, as well as significant rainfall of up to 18 inches that could bring flash flooding in some areas.

## Map of Hurricane Helene's path

The storm has been described as “very large” by Florida Governor Ron DeSantis, who warned on Thursday that it will bring with it tropical storm conditions to much of his state.

Around 14 tornado warnings were issued overnight on Wednesday, and DeSantis warned that more were likely in the coming day.

He added that Tallahassee, Florida’s capital city of 200,000 residents, could be significantly affected if the hurricane makes landfall directly on the city.

“This area has not had a major hurricane hit in quite some time, and nobody in recent memory has seen a storm of this magnitude hit,” DeSantis said.

As of 11:00 EST (16:00 GMT), Hurricane Helene was about 255 miles (405 kilometers) from Tampa, Florida, according to the NHC, with maximum sustained winds of 105 mph (165 km/h).

* 

DeSantis urged residents in the impacted regions to leave as soon as possible, as the hurricane is forecast to travel quickly towards the state.

“Every minute that goes by brings us conditions that are simply going to be too dangerous to navigate,” he said.

Michael Bobbit, a clam farmer in the island of Cedar Key on Florida's Big Bend, said that some people in his community have decided to stay behind despite the warnings.

“The last several hours have really just been a frantic effort to beg people to leave,” Mr Bobbit, 48, told the BBC. “Here in Florida, we sort of believe that we’ll just ride it out, it’s no big deal. But this is not one of those storms.”

He added that locals have been trying, "to sandbag as many buildings as we can," as well as board up windows and get the island's clam farms secured.

"The mood is sombre," Mr Bobbit said. "A lot of people when they’re leaving the island are hugging each other and crying, saying ‘I hope we have a home to go back to.'"

Reuters

People in Florida prepared sandbags to protect their properties from flooding

Governor DeSantis cautioned that people should anticipate travel disruptions. Tampa International Airport and Tallahassee International Airport were both closed on Thursday ahead of the storm.

Search and rescue teams have been mobilised should they be needed, DeSantis said, and shelters have been opened for residents in affected areas.

The hurricane has also affected the race for the White House, with the Republican candidate for vice-president, JD Vance, cancelling two events in Georgia that were planned for Thursday.

Hurricanes need sea surface temperatures of more than 27C (80F) to fuel them.

With exceptionally warm waters of the Gulf at 30-32C (86-89F), the sea surface is about two degrees Celsius above normal for the time of year.

Florida's 220-mile (350-kilometre) Big Bend Coast is where Hurricane Idalia made landfall in 2023. The area was also battered by Hurricane Debby last month.

The Florida Division of Emergency Managementof the counties in which voluntary or mandatory evacuation orders have been issued ahead of Helene.

'''
