[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/newsfeed/2024/10/31/israeli-soldiers-in-gaza-surprised-to-be-identified-by-their-online-posts?traffic_source=rss"
pub_date = "Thu, 31 Oct 2024 14:13:59 +0000"
title = "Israeli soldiers in Gaza surprised to be identified by their online posts"
bib_key = "key-1"
content = """
## Israeli soldiers in Gaza surprised to be identified by their online posts

Israeli soldiers in Gaza are seemingly surprised that they are being identified through their social media posts. Some are now worrying about possible consequences.

Published On 31 Oct 2024

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c8ekdp4r6kpo"
pub_date = "Wed, 30 Oct 2024 18:37:14 GMT"
title = "'Like a tsunami': Spaniards recount horror of deadly floods"
bib_key = "key-3"
content = '''


Reuters

The small municipality of Letur was badly hit by the floods

“When the water started to rise, it came as a wave,” said Guillermo Serrano Pérez. “It was like a tsunami.”

The 21-year old from Paiporta, near Valencia, is one of the thousands of people who experienced Tuesday night’s flash floods which.

He was driving on the motorway with his parents on Tuesday evening when the water rushed in. They survived by climbing on a bridge and abandoning their car to the fury of the floodwater.

Although heavy rain had been battering the area for hours, many, like Guillermo Serrano Pérez and his family, were caught unawares by the force of the floods.

* 
* 
* 
* 

Yet the signs had been there.

On Tuesday morning at about 07:00 (06:00 GMT), Spain's meteorological agency Aemet warned that torrential rains were forecast for the region of Valencia.

"Be very careful! The danger is extreme! Do not travel unless absolutely necessary," it said on X, before issuing a "maximum red alert".

Throughout the day, more alerts were put out, warning local authorities to prevent people from approaching the river banks.

By 15:20, the regional emergencies co-ordination centre was already publishing images of heavily flooded streets in the La Fuente and Utiel municipalities, west of Valencia.

A few hours later, it said several rivers in the area were swelling up and urged people to move away from the banks.

But in most places, it was already too late.

Chiva - about 20km away - was among the first to experience the full fury of the flash floods.

The deep ravine which traverses the town had reportedly been filling with water since Tuesday afternoon following heavy rains.

By 18:00 the town's streets had turned into raging rivers, with the force of the water dragging away cars, street lamps and benches.

Emergency services scrambled to bring assistance across the region, but the speed at which the water filled the streets was unprecedented.

Getty Images

More than 70 people are known to have died in the floods, with dozens more missing

“A very strong downpour came from above very suddenly... and the water rose a metre or a metre and a half in a few minutes," said the mayor of the town of Riba-roja de Túria.

Elsewhere in the region, news that people were missing after being swept away by floodwaters began to emerge.

Yet the civil protection did not send a warning to residents of the Valencia region to warn them not to travel on the roads until more than two hours later, after 20:00.

Many have questioned the timing of that warning, which arrived more than 12 hours after the Spanish meteorological agency had issued its first red alert.

Some say that it arrived too late for people to seek refuge on the higher floors or to get off the roads, which were busy with commuters returning home after work.

Paco had been driving from Valencia to nearby Picassent when he was caught by surprise by the flash floods that swallowed up the roads.

He told El Mundo newspaper "the speed of the water was insane" as it dragged cars away: "The pressure was tremendous. I managed to get out of the car and the water pushed me against a fence that I managed to grab on to, but I couldn't move."

"It wouldn't let me. It ripped my clothes off," he said.

Patricia Rodríguez, from Sedaví, was also caught by the flooding as she drove home from work.

She told local media that water started to rise as she sat in a line of traffic near Paiporta and the cars started floating.

“We were afraid the river was going to burst its banks because we were right in the line of fire,” she said. She managed to escape on foot with the help of another driver and watched, terrified, as a young man nearby carried a new-born baby to safety.

“It was just as well that nobody slipped, because if we had, the current would have taken us away,” she said.

Social media posts help to paint a picture of the chaos that engulfed the region as night fell.

EPA

The mayor of Paiporta, near Valencia, has confirmed that at least 34 people died in the municipality because of the flooding

In one video shared on X, wheelchair-bound residents of a care home in Paiporta could be seen trapped in a dining room with brown floodwater coming up to their knees.

Rut Moyano, a resident of Benetússer, near Valencia, chronicled the increasingly desperate situation in her town on X. Pleading for help, she said she was sheltering with neighbours on the upper floors of her building when one of them suffered a heart attack and died.

“The Civil Guard has arrived on foot but they can't access the property because there is a car stuck in the entrance,” she wrote in the early hours of Wednesday morning. “Can anyone tell me if someone else can help?”

The morning brought its own set of challenges. Daylight revealed the full extent of the devastation, with dozens of cars piled up on top of one another, destroyed businesses and entire towns covered in mud and debris.

In Valencia, a man called Juliano Sánchez was rescued with symptoms of hypothermia after clinging on to palm trees for seven hours.

“I didn't want to die,” he told El Periódico. “I grabbed onto some palm trees and held on with all my strength so the river wouldn't sweep me away.”

But many were less fortunate.

Dozens of people are still missing across the region, while those who survived have described being helpless in the face of horrific destruction.

"We saw two cars being swept away by the current and we don't know if there were people inside," a man told Las Provincias. "We'd never seen anything like it."

'''
