[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/10/24/at-brics-summit-putin-welcomes-trumps-comments-on-ending-ukraine-war?traffic_source=rss"
pub_date = "Thu, 24 Oct 2024 19:35:06 +0000"
title = "At BRICS summit, Putin welcomes Trump’s comments on ending Ukraine war"
bib_key = "key-1"
content = """


*Russian president welcomes US presidential candidate’s comments to end fighting in Ukraine as ‘sincere’.*

Russian President Vladimir Putin has welcomed comments by US presidential candidate Donald Trump on his desire to end the Ukraine conflict as “sincere”, as he concluded a summit of the BRICS bloc of developing economies in the city of Kazan, Russia.

Putin also warned the West on Thursday that it was an “illusion” to think Moscow could be defeated on the battlefield and that any peace deal would have to recognise Russia’s control of large areas of Ukrainian territory.

Putin faced calls at the summit from some of Russia’s most important allies for the fighting in Ukraine to end.

Trump has repeatedly expressed scepticism overto Ukraine and claimed that if elected, he could end the fighting in a matter of hours.

Putin said Trump “spoke about his desire to do everything to end the conflict in Ukraine. I think he is being sincere. Of course we welcome statements like this, whoever they come from.”

Some analysts believe next month’s US presidential election could be critical to future ties and the conflict in Ukraine.
## ‘Realities on the ground’

Leaders or representatives of 36 countries attended the three-day BRICS summit, including Chinese President Xi Jinping and Indian Prime Minister Narendra Modi, highlighting the failure of US-led efforts to isolate Russia over its actions in Ukraine.

The Kremlin leader said Moscow was open to considering peace initiatives and welcomed BRICS leaders offering to mediate.

But he said any deal must consider the “realities on the ground” – a reference to Ukrainian territory controlled by Russian forces.

“We are ready to look at any proposals for peace negotiations that are based on the realities on the ground. We won’t accept anything else,” he said.

Putin has previously demanded Kyiv effectively capitulate by pulling its troops back as a precondition to ceasefire talks.
## Call for end to wars in Middle East

The meeting saw the first visit to Russia from UN Secretary-General Antonio Guterres in more than two years, which drew an angry reaction from the Ukrainian government.

Guterres called for “a just peace” in Ukraine, in line with the UN Charter, international law and General Assembly resolutions. He also urged an immediate end to the fighting in Gaza, Lebanon and Sudan.
Russian President Vladimir Putin, right, greets Palestinian President Mahmoud Abbas during their meeting on the sidelines of the BRICS Summit in Kazan, Russia [Alexander Zemlianichenko/Pool via Reuters]
Russian opposition figure Yulia Navalnaya criticised Guterres for meeting Putin.

“It was the third year of the war, and the UN Secretary-General was shaking hands with a murderer,” Navalnaya said on X, posting a photo of Putin greeting Guterres.

Other world leaders at the summit also called for an end to Israel’s wars in Lebanon and Gaza, with Palestinian president Mahmud Abbas saying Israel was trying to starve civilians in Gaza and force them to flee the territory.

Chinese President Xi Jinping warned about “serious challenges” in the world and said he hoped BRICS countries could be a “stabilising force for peace”.

“We need to continue to push for a, relaunch the two-state solution and stop the spread of war in Lebanon. There should be no more suffering and destruction in Palestine and,” Xi said.

Iranian President Masoud Pezeshkian condemned the UN Security Council’s role in front of Guterres, saying international bodies “lack the necessary efficiency to extinguish the fire of this crisis”.

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/ce891r9pd48o"
pub_date = "Thu, 24 Oct 2024 16:04:19 GMT"
title = "Bowen: Gaza nurse who filmed moments after Israeli strike describes chaos and grief"
bib_key = "key-3"
content = '''


BBC

Paramedic Nevine al Dawawi says Jabalia has been "besieged" by Israeli forces

From the outside, it is hard to comprehend the depth of suffering experienced by civilians in Gaza.

On Monday 21 October, a video emerged from Jabalia that gave an unusually detailed insight into the pressure and the horror imposed on civilians by Israel’s current offensive in northern Gaza. Watching it, you feel almost like an eyewitness.

Every day, like many journalists who are forced to report the war from outside Gaza because, I watch many videos that emerge online, harrowing scenes of wounded, dying and bereaved people in hospitals, of men in the rubble rescuing survivors and digging out bodies, and civilians forced to move by the Israelis, walking through thick sand where roads used to be, past the unrecognisable ruins.

* 
* 
* 

They are all horrible to see, and so was the one that came from the attack in Jabalia on Monday morning. But for me it was unusual because it showed the pain, grief, chaos, panic and hopelessness in the seconds and minutes immediately after an attack.

The moment is so extreme that taking out a phone to film it is the last thing most people do. Over many years as a reporter in wars, I have seen and experienced the same disbelief and shock. It takes time for the brain to catch up with the utterly changed reality that your eyes are seeing.

The Jabalia Boys Elementary school was attacked just after 09:00 in the morning, on 21 October. It was no longer a place of learning but had been turned into a shelter for displaced civilians, like many schools in Gaza run by UNRWA, the UN agency for Palestinian refugees. All the ones still standing, that is.

In the video, a paramedic called Nevine al Dawawi, increasingly panic-stricken, runs between dead and dying civilians, using her phone to document what is happening (when I reported this first, on the day of the strike, she was misidentified as Nabila.)

We managed to track down Nevine in Gaza City. She was able to give us her own account of what happened on Monday morning. She answered questions, and much more composed now, she played back the video.

In it, she is agitated and scared, running between civilians lying in their own blood, next to dead bodies.

## 'I don't have anything to stop the bleeding'

“Calm down,” she screams at a badly hurt woman sitting in a pool of blood.

“I swear I don’t have anything to stop the bleeding.”

She runs down a passage pockmarked by shrapnel. On a stairwell she sees more casualties, turns away in horror, picks up a bag and says "let’s go, so no-one else gets killed".

A man’s voice on the video says, “stay with us Nevine.” Grabbing the bag, which is full of wound dressings, she goes back to the stairwell that is running with blood. A child’s voice says, please help, my sister is dying, please help me.

A woman says my children are gone. Nevine asked how she knew.

“Look at them,” the woman says. One is very still, the other has a severe head wound and is either dead or dying.

Nevine hands over dressings, even though it is too late. They are all she has, and she is the only paramedic there.

Nevine told us that the woman on the stairs whose children were killed was Lina Ibrahim Abu Namos. Journalists working for the BBC found her in Kamal Adwan hospital in Jabalia where she is being treated for shrapnel injuries. Two of Lina’s seven children were killed, her eldest daughter and her only son.

Her husband wasn’t with them when the attack happened, as he was already being treated for wounds sustained in an earlier attack.

“I saw my daughter dying, with my own eyes. She was dying in front of me. I couldn't stop it, and she was my eldest, my whole life, honestly, my entire life. When your eldest dies in front of you…”

“I couldn’t save her, and I was also wounded. I couldn’t handle myself, I found myself falling on the ground. I started crawling towards her.”

Lina Ibrahim Abu Namos has lost two of her children since the war started

Nevine, the paramedic, explained that they had been "besieged" at the school for 16 or 17 days. Above them was the buzz of quadcopters, small drones used extensively by the IDF. It has a range of them, for surveillance and espionage, to issue orders through loudspeakers, for dropping bombs or firing at Palestinians they want to kill.

“We were living in so much fear. When the school was hit, we had people killed and injured. There was nothing there to eat or drink. The water tanker that was usually sent to us was bombed by the Israelis. It was like that for days. Three days ago, a quadcopter descended on the school at nine in the morning, giving us an ultimatum to get out by 10. The quadcopter loudspeaker said we had to evacuate the school because we were in a dangerous fighting zone.”

“We didn’t have time to pack our stuff. It gave us just one hour. After just 10 minutes, Israeli airplanes bombed the school. It was a big massacre with over 30 wounded and more than 10 killed.”

In the video, the wounded and dead on the bloody stairs are not the only casualties. Nevine leaves the stairwell, and runs to a man probably in his sixties, who is leaning over a pile of bags with his head in his hands. She looks to see if somehow, he has survived a severe neck wound and screams when she sees that he has not.

“Help him, he’s dead – it’s Uncle Abu Mohammed.”

Three days later I sent questions for a Palestinian freelance journalist to ask her at al Ahli hospital in Gaza City. One was about Abu Mohammed.

“He was our neighbour. His two sons were also killed… one had half his head gone.”

She talked our reporter through the video as she played it back on her phone.

“The video showed girls torn to pieces. It also shows men with their intestines protruding from stomach wounds… A 10-year-old boy had his bowels bulging outside his stomach. His mum was killed, injured in the heart.”

“Some women who were taking cover were also injured and others killed. A cleaner at the school was shredded into pieces. A 12-year-old girl had a leg blown off. So did a woman displaced from, a town in Gaza’s north. She was aged between 35 and 40.”

The day before the attack on the school, as Israel’s offensive intensified, Tor Wennesland - the senior UN diplomat in Jerusalem - issued a strong statement.

“The nightmare in Gaza is intensifying. Horrifying scenes are unfolding in the northern Strip amidst conflict, relentless Israeli strikes and an ever-worsening humanitarian crisis.”

“Nowhere is safe in Gaza. I condemn the continuing attacks on civilians. This war must end, the hostages held by Hamas must be freed, the displacement of Palestinians must cease, and civilians must be protected wherever they are. Humanitarian aid must be delivered unimpeded.”

Israel insists that it acts in self-defence, and claims its forces respect the laws of war. Almost every day for the last year in Gaza, and more recently in Lebanon it says that civilians get killed because armed groups use them as human shields.

We put that to the paramedic, Nevine al Dawawi.

The IDF claimed Hamas was using civilians as human shields, is that true?

“No, Hamas was not using civilians as human shields. They were protecting us and standing with us.”

Getty Images

Families fleeing Israeli army operations in Jabalia take the main Salah al-Din road towards Gaza City on 23 October.

For many in Israel, her statement that Hamas were in the area will be taken as a justification for the horrors that the IDF brought down on the civilians just after 9 in the morning on Monday 21 October.

But war crimes lawyers will ask whether the attack was justified. The laws of war say that civilians must be protected, and that casualties inflicted on them should be in proportion to the military threat faced by an attacking force.

If senior Hamas commanders were there, or a big concentration of fighters preparing to fight, perhaps the attack could be justified by the Israel Defense Forces’ own lawyers.

But if Hamas, whose structure as a fighting force has been dismantled in a year of relentless Israeli attacks, had only a few local men with guns in the area, then the attack would breach the law.

In the unlikely event that the Palestinians in the video ever had a day in court, their lawyers could say that the military threat to the IDF at that moment did not justify wounding 30 civilians, inflicting life changing injuries, and killing more than 10 others, including many children.

I am forced to use conditional tenses because I am writing this in Jerusalem, not after interviewing eyewitnesses at the scene of the attack in Jabalia in Gaza. Reporters will always struggle to get to get to the best possible version of the truth they can find when they are stopped from getting to the place where the story happened.

Israel allowed reporters into their border communities along the border with Gaza in the days after the Hamas attacks last year. I was in Kfar Azza kibbutz when they were still recovering the bodies of dead Israelis, as soldiers checked buildings with bursts of gunfire. They wanted us to see where Hamas had killed around 1,200 Israelis, mostly civilians, and dragged more than 250 into captivity in Gaza.

The evidence is piling up that Israel has done things in Gaza that it does not want journalists to see, which is why they will not let us cross into the territory, except on rare and highly controlled visits with the army. I have been in only once, in the first month of the war, when Israeli firepower had already turned the areas of northern Gaza that I saw into a wasteland.

As a result, journalists rely on videos and statements that emerge from Palestinians inside Gaza, including some very brave journalists, and from international diplomats, medics and aid workers who are allowed into Gaza, and witnesses like Nevine with smartphones.

In the hospital, Lina Ibrahim Abu Namos was haunted by her loss of her eldest daughter, her only son, and everything they called home.

“I had seven children, and now I only have five left… What can I say? I don’t even know. By God, they have broken our hearts. We are exhausted, emotionally drained. We’ve lost everything.”

“What crime have the children committed? What have they done? What have we done to deserve this?”

“What have we done to the Israelis? I swear, they’ve destroyed our children.”

"I’m so scared. I don’t eat or drink. Nothing. All I need is for my children to stay around me, because we are scared and we’ve been displaced from one place to another. What is left for my daughters and for me? There’s no home, nowhere safe, nothing. I’m just one of many people with nowhere to go, no safety. I'm exhausted.”

'''

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/videos/c9vn8z2wwy9o"
pub_date = "Thu, 24 Oct 2024 17:11:03 GMT"
title = "Watch Steve Rosenberg challenge Vladimir Putin over Ukraine war"
bib_key = "key-4"
content = '''
The BBC's Russia Editor asked Vladimir Putin about 'justice and security" in light of the Ukraine war.

In response to Steve Rosenberg's question, Putin said the Nato expansion "violates" Russian security. "There is no justice here and we want to change that", he added.

Rosenberg also asked the Russian president about recent MI5 intelligence reports which said Russia's intelligence agency has been on a mission to generate "sustained mayhem on British and European streets".

"It's complete nonsense", Putin replied.'''

[[content]]
section = "Science"
source = "math updates on the arXiv.org e-print archive."
link = "https://arxiv.org/abs/2410.17254"
pub_date = "Thu, 24 Oct 2024 00:00:00 -0400"
title = "Measure and dimension theory of permeable sets and its applications to fractals"
bib_key = "key-6"
content = '''


> Abstract:We study {\\it permeable} sets. These are sets \\(\\Theta \\subset \\mathbb{R}^d\\) which have the property that each two points \\(x,y\\in \\mathbb{R}^d\\) can be connected by a short path \\(\\gamma\\) which has small (or even empty, apart from the end points of \\(\\gamma\\)) intersection with \\(\\Theta\\). We investigate relations between permeability and Lebesgue measure and establish theorems on the relation of permeability with several notions of dimension. It turns out that for most notions of dimension each subset of \\(\\mathbb{R}^d\\) of dimension less than \\(d-1\\) is permeable. We use our permeability result on the Nagata dimension to characterize permeability properties of self-similar sets with certain finiteness properties.

## Submission history

From: Gunther Leobacher []
**[v1]**Thu, 3 Oct 2024 18:57:50 UTC (1,764 KB)

'''
