[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/unmute/2024/10/24/ilan-pappe-on-being-censored-for-pro-palestine-stance?traffic_source=rss"
pub_date = "Thu, 24 Oct 2024 14:41:46 +0000"
title = "Ilan Pappé on being censored for pro-Palestine stance"
bib_key = "key-1"
content = """
## Ilan Pappé on being censored for pro-Palestine stance

“We are not intimidated by them and that’s why they are using everything in their ammunition to silence us.” Israeli historian Ilan Pappé discusses his experience of being stopped at an airport in Detroit, Michigan and being interrogated by Homeland Security due to his pro-Palestine stance. He says that attempts to suppress freedom of speech have intensified since October 7.

Published On 24 Oct 2024

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cvgx3zjvjg3o"
pub_date = "Thu, 24 Oct 2024 10:25:01 GMT"
title = "Lebanon: Satellite imagery reveals intensity of Israeli bombing"
bib_key = "key-3"
content = '''


Getty Images

Damaged buildings in a residential area following an Israeli attack on Dahieh suburb in Beirut

Israel's intensified bombing campaign of Lebanon has caused more damage to buildings in two weeks than occurred during a year of cross-border fighting with Hezbollah, according to satellite-based radar data assessed by the BBC.

Data shows that more than 3,600 buildings in Lebanon appear to have been damaged or destroyed between 2 and 14 October 2024. This represents about 54% of the total estimated damage since cross-border hostilities between Israel and Hezbollah broke out just over a year ago.

The damage data was gathered by Corey Scher of City University of New York and Jamon Van Den Hoek of Oregon State University. They compared radar satellite images to reveal sudden changes in the height or structure of buildings which indicate damage.

Wim Zwijnenburg, an environmental expert from the Pax for Peace organisation, reviewed the satellite-based radar data and warned of the impact of Israel’s bombing.

“The Israeli military campaign seems to be creating a ‘dead zone’ in the south of Lebanon to drive out the population, and making it difficult for Hezbollah to re-establish positions, at the cost of the civilian population,” he said.

Cross-border hostilities between Israel and Hezbollah broke out after the armed Lebanese group started firing rockets in and around northern Israel in support of Palestinians on 8 October 2023, the day after its ally Hamas’s deadly attack on southern Israel.

Israel invaded southern Lebanon in a dramatic escalation on 30 September to destroy, it said, Hezbollah weapons and infrastructure in “limited, localised, targeted raids”.

Satellite photos, radar imagery, and military records show recent Israeli bombardment in Lebanon has focused on the southern border region. It has also expanded to central and northern areas, including the Bekaa Valley and Beirut's southern suburbs.

The Israeli army said it hit thousands of Hezbollah targets across Lebanon, including the capital, Beirut.

Most of the strikes on Beirut have targeted Dahieh, a southern suburb that is home to thousands of civilians. The Israeli military claims the area is home to Hezbollah’s command headquarters.

A series of Israeli strikes on buildings in the area killed Hezbollah's leader Hassan Nasrallah on 27 September.

Separate data from the US-based Armed Conflict Location and Event Data Project (Acled), which has been analysed by the BBC, indicates at least 2,700 attacks by the Israeli military on Lebanese areas from 1 September until 11 October 2024. While these attacks primarily focus on southern border areas, they have also extended to northern and central regions.

Hezbollah has carried out around 540 attacks against Israel in the same timeframe, according to Acled. Each Hezbollah attack can include a barrage of rockets, missiles and drones.

The Israeli military says air strikes in Lebanon are targeting Hezbollah infrastructure.

It regularly adds it wants to ensure the safe return of tens of thousands of residents of Israeli border areas displaced by attacks from the Iran-backed group.

About 60,000 people have been evacuated from northern Israel because of near-daily attacks by Hezbollah. But some rockets have reached further south and damaged homes in and around the coastal city of Haifa.

On the Lebanese side, many Israeli air strikes targeted the city of Tyre, the Bekaa Valley, and Beirut, according to the BBC’s analysis of the latest monthly data collected by Acled.

Lebanon's government says up to 1.3 million people have been internally displaced, whilst Prime Minister Najib Mikati warned of the "largest displacement” in the country's history.

The Israel Defense Forces (IDF) has been issuing evacuation orders to residents across the country, including areas of Beirut.

In the south, the army instructed residents of several villages to leave their homes and "immediately head north of the Awali River," which meets the coast about 50 km (30 miles) from the Israeli border.

“This is a humanitarian catastrophe,” Gabriel Karlsson, Middle East Manager at the British Red Cross in Beirut, told the BBC.

He said there are insufficient shelters to accommodate so many evacuees.

“I saw children sleeping in the streets,” Karlsson added, urging humanitarian organisations to coordinate their efforts to address the escalating crisis.

Lebanese officials say at least 2,350 have been killed and over 10,000 injured in Israeli attacks. The Lebanon health minister said many casualties were civilians.

On the Israeli side, 60 people have been killed and more than 570 wounded by Hezbollah attacks, Israeli authorities say.

“Collateral damage is inevitable in war”, Amos Yadlin, the former head of Israeli military intelligence, told the BBC.

The retired major-general blamed Hezbollah for the war and claimed Israel’s ground offensive would force the group out from the border areas.

Zwijnenburg, from the Pax for Peace organisation, however, has warned of the impact of Israel’s military campaign on civilians and the populated areas.

“The heavy blast radius kills and maims civilians nearby”, he said, in reference to Israeli air strikes.

“Open-source data combined with satellite imagery also showed that civilian infrastructure such as irrigation channels, gas stations and electricity grids were damaged, which is worsening the humanitarian situation,” he added.

'''

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c937p1vzrx0o"
pub_date = "Thu, 24 Oct 2024 14:50:19 GMT"
title = "Turkey strikes Kurdish sites after attack kills five near Ankara"
bib_key = "key-4"
content = '''


AP

Turkey's government says its military has struck sites in Iraq and Syria linked to Kurdish militant group the PKK, after blaming it for an attack near Ankara that killed at least five people.

The Turkish government said that the strikes since Wednesday had killed 59 people it described as "terrorists". A Kurdish-led militia in Syria said 12 civilians died in the north and east of the country.

Various videos from the attack earlier on Wednesday show at least two people firing guns around the entrance of Turkish Aerospace Industries (TAI), which is located some 40km (25 miles) outside the capital.

No group has claimed responsibility for the attack, in which 22 people were injured.

The Turkish defence ministry said that since Wednesday night and Thursday morning, its strikes had “successfully eliminated” 47 targets including caves, shelters, warehouses and other facilities in northern Iraq and Syria.

President Recep Tayyip Erdogan called the attack on TAI "heinous" in a post on X.

Interior Minister Ali Yerlikaya said shortly after the attack that the two perpetrators, a woman and a man, had been "neutralised".

On Thursday, Yerlikaya said the attackers had been identified as PKK members Ali Orek and Mine Sevjin Alcicek.

The Kurdistan Workers' Party (PKK) is banned as a terrorist organisation in Turkey, the US and UK, and has been fighting against the Turkish state since the 1980s for greater rights for the country’s significant Kurdish minority.

The Kurdish-led Syrian Democratic Forces (SDF) said on Thursday morning that Turkey had launched a "new wave" of attacks, including on "civilian gatherings", killing 12 people.

According to the the Syrian Observatory for Human Rights, Turkish warplanes and drones targeted infrastructure in northern and eastern Syria.

It added that the region had seen “intensive raids” in the cities of Hasakah, Raqqa, Kobani, Manbaj and Tal Rifaat.

The watchdog said Turkish forces resumed attacks on Thursday morning, with targets including a checkpoint near a train station, a bakery and power station.

The Turkish defence ministry said earlier that "all kinds of precautions were taken to prevent harm to innocent civilians, friendly elements, historical and cultural assets and the environment".

Videos show how Ankara attack unfolded

Turkish Vice-President Cevdet Yilmaz said four of the victims of Wednesday's attack near Ankara were TAI employees, while the fifth was a taxi driver.

The victims were named by Turkey's state-run news agency as Cengiz Coskun, a quality control officer, Zahide Guclu, a mechanical engineer, security guard Atakan Sahin Erdogan, another employee called Huseyin Canbaz and Murat Arslan, the taxi driver.

Local media had earlier reported that the attackers killed the cab driver before taking his vehicle to carry out the attack.

The blast took place around the time of a shift change, and staff had to be directed to shelters, they said.

Yerlikaya also confirmed that seven special ops forces members were among the 22 who were injured in the attack.

UK Prime Minister Sir Keir Starmer said he was "appalled" by the attack in Ankara.

In a post on X, he wrote: "We stand shoulder to shoulder with Turkey as a Nato ally and close friend."

President Erdogan - who at the time was in Russia for the Brics summit - condemned what he called a "vile terror attack" during a meeting with Russian President Vladimir Putin, in remarks broadcast live on TV.

He later posted a lengthy statement on X, saying that security forces acted quickly to neutralise the threat, and that "no terrorist organisation, no evil focus targeting our security will be able to achieve their goals".

Turkish authorities have imposed a media blackout on details of the attack, and users in large areas of the country have reported not being able to use social media sites like YouTube, Instagram, Facebook and X.

The president of Turkey’s Radio and TV Supreme Council, Ebubekir Sahin, warned that all images relating to the incident should be removed from social media, and urged users not to share images which “will serve the purpose of terrorism”.

TAI is a key player in Turkey’s aerospace industry, designing, developing and manufacturing various aircraft for commercial and military use.

It is the company designated by the Nato member to be the licensed manufacturer for the US-designed F-16 fighter jets. TAI also plays a role in modernising older aircraft for use by the Turkish military.

The firm's two principal owners are the Turkish Armed Forces and a civilian arm of Turkey's government charged with improving its defence capabilities and managing military procurement.

The blast took place as a major trade fair for defence and aerospace industries was going on in Istanbul this week.

'''

[[content]]
section = "Science"
source = "math updates on the arXiv.org e-print archive."
link = "https://arxiv.org/abs/2410.17254"
pub_date = "Thu, 24 Oct 2024 00:00:00 -0400"
title = "Measure and dimension theory of permeable sets and its applications to fractals"
bib_key = "key-6"
content = '''


> Abstract:We study {\\it permeable} sets. These are sets \\(\\Theta \\subset \\mathbb{R}^d\\) which have the property that each two points \\(x,y\\in \\mathbb{R}^d\\) can be connected by a short path \\(\\gamma\\) which has small (or even empty, apart from the end points of \\(\\gamma\\)) intersection with \\(\\Theta\\). We investigate relations between permeability and Lebesgue measure and establish theorems on the relation of permeability with several notions of dimension. It turns out that for most notions of dimension each subset of \\(\\mathbb{R}^d\\) of dimension less than \\(d-1\\) is permeable. We use our permeability result on the Nagata dimension to characterize permeability properties of self-similar sets with certain finiteness properties.

## Submission history

From: Gunther Leobacher []
**[v1]**Thu, 3 Oct 2024 18:57:50 UTC (1,764 KB)

'''
