[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cly2z73127vo"
pub_date = "Thu, 07 Nov 2024 08:41:52 GMT"
title = "Europe's leaders face up to Trump victory at Hungarian summit"
bib_key = "key-1"
content = '''


Getty Images

Volodymyr Zelensky was among the dozens of leaders converging on Budapest with Ukraine uppermost in their minds

The re-election of Donald Trump to the White House is focusing minds in Europe, and with dozens of leaders meeting in Budapest, they have the perfect chance to talk it through.

Trump's first term in office saw a dramatic souring of relations. He was angry European countries didn’t pay more towards their own security.

He was livid about the US trade deficit with Europe. And he seemed particularly irate with EU big power Germany on both those counts. Just ask German ex-Chancellor Angela Merkel.

So what will the future Trump presidency mean for the continent? And in particular, for Ukraine?

Reuters

Europe's leaders converge on a football stadium in Budapest for their summit on Thursday

Ukraine's Volodymyr Zelensky is in the Hungarian capital for a meeting of the European Political Community. It was the brainchild of French President Emmanuel Macron - launched following Russia’s full-scale invasion of Ukraine as a talking-shop to jointly tackle continental challenges.

The fear here is that the new US administration will slow, if not stop, the flow of American military aid to Kyiv. The US has been the largest single donor to Ukraine. By far. And Europe will struggle to take up the slack.

Trump boasted in the past he could end the war with Russia in a day. What isn’t clear is whether he wants Ukraine to win.

Europe’s leaders, notably UK Prime Minister Sir Keir Starmer, Macron and German Chancellor Olaf Scholz, have repeatedly pledged to stand by Ukraine.

Zelensky will appeal to them on Thursday to stay true to their word.

Things look challenging for Kyiv, to say the least.

Not only is the future of US military aid now insecure, there’s a question mark too over Ukraine’s second largest donor, Germany. Its three-party coalition government crumbled late on Wednesday.

On top of all this, the host of Thursday’s meeting is none other than Hungary’s Trump-enthusiastic Prime Minister, Viktor Orban. Also well-known for his close ties to Moscow, his reluctance to impose sanctions on Russia and to provide self-defence weapons to Ukraine.

Getty Images

Ukraine's Volodymyr Zelensky said he had had an "excellent" phone call with Trump on Wednesday

He has repeatedly called on the EU to demand an "unconditional and immediate ceasefire" between Ukraine and Russia: going against the insistence among Ukraine’s Western allies to date that Kyiv should dictate its own terms.

Orban describes Trump as being in what he calls his "pro-peace" camp.

All that said, President Zelensky and others in Budapest this Thursday hope to maintain friendly relations with the new Trump administration for as long as possible.

The mainly gushing congratulatory messages from Europe’s leaders on social media made that abundantly clear. But Trump will know that most of them favoured his Democrat rival for the presidency, Kamala Harris.

The US electoral race was always predicted to be tight, and EU officials insist they are better prepared for Trump 2.0 than in 2016, when they were taken by surprise.

But Trump’s isolationism still worries Europe deeply.

The continent looks to the US for security. It has done so since the end of World War Two. It seeks protection from Russian expansionism and help in defending Ukraine. Problem is: Trump is no fan (and that’s putting it politely) of Nato, the transatlantic military alliance.

Getty Images

Viktor Orban was Europe's first leader to congratulate Donald Trump on his victory

Trade is another concern, especially for the EU.

The US is its biggest trade partner. But Trump is protectionist. He loves slapping tariffs on imports, he says.

This is bad news for Europe’s already sluggish economies. Like export-reliant Germany, with its ailing automobile industry. The European Commission says it’s ready, if needs be, with retaliatory measures, but would rather avoid marching down the trade war path with Trump.

Unity is another niggle. Trump, with his America First policy, not unlike Russia's Vladimir Putin or Xi Jinping of China, who push their own nationalist agendas on the world stage, would prefer not to face off against a strong, united Europe. Divide and rule is their preference.

Viktor Orban is not the only huge Trump fan here. So is Slovakia’s prime minister, and, to an extent, Italy’s premier too. They lean towards Trump in a way that divides them from most of the rest.

Brussels frets about other EU member states now potentially rushing to secure good bilateral relations with Trump at the expense of unity. Leaving the bloc weaker.

But an EU diplomat I spoke to, who asked not to be named in order to speak freely, believes the opposite could also be true.

“We in Brusselsabout Brexit at the time,” he told me.

“We thought other member states would follow the UK out the EU door. But the reverse happened. EU countries melded together more through the Brexit process. Donald Trump might have the same effect on us. Drive us closer together. Force us to be more self-reliant.”

Just before US election day, Polish Prime Minister Donald Tusk, himself a former big figure in Brussels proclaimed on X: “The future of Europe no longer depends on presidential elections in the US, but primarily on Europe itself.”

Maybe. Or maybe not.

Another, rather scared school of thought amongst traditional politicians in Europe is that this victory for Trump could prove a boost for right-wing nationalists far closer to home.

European populists who share his belief that they are the true voice of voters: upset about the economy, about immigration, about the state of their respective countries and demanding change now.

* 
* 
* 
*'''

[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/11/7/trumps-return-to-white-house-worries-lebanese-palestinian-civilians?traffic_source=rss"
pub_date = "Thu, 07 Nov 2024 14:16:54 +0000"
title = "Trump to worsen our plight: Palestinian, Lebanese victims of Israel’s wars"
bib_key = "key-3"
content = """
**Deir el-Balah, Gaza, Palestine, and Beirut, Lebanon**– Palestinian and Lebanese civilians are bracing for more devastation once Donald Trump begins his second term as president of the United States in January.

While millions of Trump supporters celebrate his victory, many in the Middle East are looking on with trepidation.

In Gaza, the occupied West Bank and Lebanon, there are fears the loyal ally of Israel will embolden its prime minister, Benjamin Netanyahu, and far-right coalition government to escalate regional conflicts and destroy any possibility of Palestinian self-determination.

“I have no trust in America,” said Abu Ali, an 87-year-old in Gaza who has been uprooted from his home like most people there. “I’m expecting the war in Gaza to get even worse [under Trump].”
A grieving mother comforts a boy after her son was killed in an Israeli attack in the village of al-Shuhada near Jenin in the Israeli-occupied West Bank [Raneen Sawafta/Reuters]
US President Joe Biden’s outgoing administration hasIsrael in its campaign in Gaza.

Since the Hamas-led attacks on southern Israel on October 7, 2023, during which 1,139 people were killed and 250 taken captive, Israel’s genocide against Palestinians in Gaza – using US weapons – has killed more than 43,000 Palestinians and uprooted almost the entire population of 2.3 million people.

Palestinians there fear Trump will now greenlight plans to expel them from the strip.

The Republican president-elect has accused Biden, a Democrat, of restraining Israel in Gaza and made a vague promise to help Israel toif re-elected.

“I don’t know if the situation will improve under Trump. He might just [allow Israel] to deport us all [from Gaza] instead of killing us,” Abu Mohamad said with a hint of sarcasm from a displacement camp in Gaza.

Abu Ali believes Palestinians are at the mercy of whoever holds power in the US.

As a survivor of the Nakba (“catastrophe”), the expulsion of 750,000 Palestinians by Zionist militias during the creation of Israel in 1948, he said he has witnessed several US presidents support Israeli atrocities against his people.

He expects that trend to continue under Trump and stressed that neither the Nakba nor Israel’s ongoing genocide in Gaza should be referred to as a “war”.

“There are no wars [between Israel and Palestine],” he told Al Jazeera. “It wasn’t a war then. And this isn’t a war [in Gaza]. It’s a genocide.”
A Palestinian woman who lost members of her family in an Israeli strike grieves near their bodies at Nasser Hospital in Khan Younis in the southern Gaza Strip on November 3, 2024 [Bashar Taleb/AFP]## The view from Lebanon

In Lebanon, many people expect Trump to maintain or increase support for Israel’s war effort.

Israel claims to be battling the Lebanese armed group Hezbollah, yet observers accuse Israel of waging a war against the country’s Shia community.

In Lebanon, political posts are allocated proportionally based on the country’s religious makeup. The president is always a Maronite Christian, the prime minister a Sunni Muslim and the speaker of parliament a Shia Muslim.

Since Lebanon’s civil war, which lasted from 1975 to 1990,has consolidated control over the Shia community by mixing religion, identity and resistance into a political movement that has resonated with many people. Hezbollah has also repressed opponents.

Over the past month, Israel has escalated its war against Hezbollah byin southern Lebanon and the Bekaa Valley. Residents from entire villages and districts have been uprooted by Israeli fire, which has razed their homes and stoked fears of permanent displacement.

Ali Saleem, who was forced out of the southern city of Sour, said the war will continue under Trump. He said the president-elect may present a ceasefire proposal that is favourable to Israel but not to Hezbollah or Lebanon.

“Trump will put an offer on the table, and he’ll say, ‘Do you want to end the war or not?’” Selim, 30, told Al Jazeera. “If we say no, then war will continue.”

Ali Aloweeya, 44, added that Trump will likely defend “Zionist interests” in the region.

He fears Trump might even allow Israel to try to build illegal settlements in southern Lebanon, as some far-right Israeli activists and political officials have called for.

“If Trump returns and works again for the interests of the Israelis, then we will resist. We are a people of resistance.”
A woman in front of a bombed branch of the al-Qard al-Hassan finance group in al-Shiyah, Beirut, Lebanon [File: Wael Hamzeh/EPA-EFE]## Fear of annexation

During Trump’s first presidential term from 2017 to 2021, he adopted measures that harmed Palestinians in the occupied territory and surrounding region.

He cut off US funds to the UN Palestinian aid agency (UNRWA) and broke with decades of policy by moving the US embassy from Tel Aviv to Jerusalem.

Palestinians saw the moves as an attempt to upend their right to return to their homeland – as stipulated in UN Resolution 194 – and force them to surrender occupied East Jerusalem as the capital of a future Palestinian state.

Israel annexed East Jerusalem and occupied Arab lands after defeating Arab armies in the Six-Day War in 1967.

Tasame Ramadan, a Palestinian human rights activist, now fears Trump may allow Israel to annex large swaths of the West Bank. Activists, analysts and rights groups saidalready.

“As Palestinians, we don’t expect anything positive from Trump. His decisions are unpredictable, but he often ignores Palestinian voices, and his decisions have lasting impact on Palestinians,” said Ramadan, who lives in Nablus, a city in the West Bank.

She noted that Trump in 2019Israel’s sovereignty over Syria’s occupied Golan Heights, contravening international law.

She’s preparing for similar policies that could harm – even kill – Palestinian aspirations for self-determination.

“Trump’s action ignores our rights and our hopes for freedom and for a sovereign Palestinian state,” she told Al Jazeera.

“But I don’t think Palestinians would be happy if [US Vice President Kamala] Harris had won the election either. She deserved to lose due to her stance on the situation in Palestine and not stopping the genocide.

“In both cases, neither of these two [candidates] were our best options.”"""

[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/newsfeed/2024/11/7/israeli-attacks-on-gaza-and-lebanon-as-us-election-was-happening?traffic_source=rss"
pub_date = "Thu, 07 Nov 2024 13:31:11 +0000"
title = "Israeli attacks on Gaza and Lebanon as US election was happening"
bib_key = "key-4"
content = """
## Israeli attacks on Gaza and Lebanon as US election was happening

Israeli attacks on Lebanon and Gaza continued while attention was focused on the US elections and Donald Trump’s victory.

Published On 7 Nov 2024

"""
