[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cqjrwg9dly1o"
pub_date = "Thu, 03 Oct 2024 14:09:00 GMT"
title = "Missile attack on Israel lays bare deep divisions among Iranians"
bib_key = "key-1"
content = '''


Getty Images

Iran launched almost 200 missiles towards Israel, which said it intercepted most of them

Iranians have been expressing a mixture of pride, uncertainty and fear since their country launched a large-scale ballistic missile attack on Israel on Tuesday night.

Within minutes of the attack starting, Persian social media feeds were filled with shaky videos showing the flashes of the missiles flying overhead.

Iran’s state television broadcast pictures of groups of people cheering on the streets, waving flags and chanting “Death to Israel”.

But the mood was different online, with not everyone expressing support for the attack.

Some shared tense scenes and heated debates about a possible war between the arch-foes, after decades of keeping their conflict largely in the shadows.

The contrasting reactions laid bare the deep divisions in Iran, where there is widespread discontent at the clerical establishment and frustration over the economic troubles caused by sanctions.

On one side of the debate are those who support the government's actions with nationalist pride, while on the other are those who fear war, economic collapse and further suppression of domestic reform movements.

Iran’s Revolutionary Guards said Tuesday’s missile strike successfully targeted Israeli military and intelligence bases and that it was retaliation for recent killings of the leaders of its allies Hamas and Hezbollah.

The Israeli military described the attack as "indiscriminate" and said that while it had been largely thwarted by air defences, there had been casualties and millions of Israelis had been sent running to bomb shelters.

Israel's prime minister Benjamin Netanyahu has warned that Iran will pay for the "big mistake".

For many supporters of the Iranian government, the attack represented a proud moment of defiance.

“Bravo to [Supreme Leader Ayatollah Ali] Khamenei! Bravo to the Revolutionary Guards!” shouted a young woman in a clip that went viral.

Such sentiment frustrated other Iranians online.

“Please distinguish between the people and the Revolutionary Guards; we are under immense pressure,” pleaded a middle-aged man in a video shared on social media.

Some Iranians felt the strike was an unnecessary provocation that would only result in making their lives worse.

“We have no choice but to protect our country, but we are the ones who suffer the consequences,” said a concerned resident of the capital, Tehran.

In the hours after the strikes, rumours surfaced that Israel might respond by targeting Iran’s oil infrastructure, which is an important part of the country’s economy.

Videos quickly surfaced showing petrol stations overwhelmed, with long queues of people as they rushed to fill up their vehicles, fearing future shortages.

Getty Images

Supporters of Iran's government celebrated on the streets after learning of the attack

The missile attack has also diminished hopes for diplomatic progress with the West and other countries in the region.

The election of Masoud Pezeshkian as the new president in July had sparked optimism among those with moderate views. Some people saw him as a potential bridge in easing regional tensions.

But one BBC Persian viewer lamented that “this attack is another step away from diplomacy and a step closer to conflict”.

“I fear this war might be used as an excuse to intensify the crackdown of us, who are fighting for freedom,” a young activist said, referring to the nationwide “Woman, Life, Freedom” protests that erupted two years ago.

Many worry that a new conflict could not only undermine calls for reform, but also empower the government to further suppress internal dissent.

Unlike after previous escalations, this time there’s a growing fear of a potentially strong retaliatory response from Israel.

And many believe that Israel’s advanced military capabilities could bring unprecedented destruction if a full-scale war broke out.

“No-one wants war, not the people, not even the officials,” said a commentator on social media.

This sense of vulnerability has made the situation feel more precarious than ever before.

Amid the growing tensions, some people even called for regime change.

“The only way to save Iran is not through war, but through toppling the current regime,” said another BBC News Persian viewer, urging the West to support Iranians in their struggle against the government.

However, many believe the country’s future should be decided internally, free from any foreign intervention, to avoid the potential chaos that outside interference might cause.

'''

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c9wkvnwdqpqo"
pub_date = "Thu, 03 Oct 2024 16:49:40 GMT"
title = "TikTok influencer 'Mr Prada' arrested for second degree murder"
bib_key = "key-2"
content = """


A popular TikTok creator has been charged with second degree murder in the death of a 69-year-old Louisiana therapist.

Terryon Thomas, also known as Mr Prada to his 4.3 million followers, was arrested in Dallas, Texas on Tuesday afternoon after he was allegedly seen driving a stolen car that police said belonged to William Abraham, the therapist.

Mr Abraham’s body was found wrapped in a tarp on Sunday in Baton Rouge, Louisiana.

Police said he died from blunt force trauma to the head, describing it as a “very physical, very violent death”.

Mr Thomas, 20, has been charged with second degree murder and obstruction of justice, according to the East Baton Rouge Sheriff’s Office, and is in custody in Dallas, Texas awaiting extradition to Louisiana.

“This is an ongoing investigation that will take time to gather further evidence,” Casey Hicks of the East Baton Rouge’s Sheriff’s Office said in a statement.

“I hope that this arrest may bring some closure and assurance to friends and family,” she said.

Mr Abraham’s body was found in a blue tarp on the east side of US Highway 51 on Sunday, police said, adding that they later discovered his car had been missing.

Police said they later uncovered surveillance footage that purportedly identified Mr Thomas as the last person seen driving the therapist’s vehicle.

They then attempted a traffic stop on Mr Thomas, but he allegedly resisted arrest, backed up into the officers’ car and fled.

Police searched Mr Thomas’ apartment in Baton Rouge, where they allegedly found evidence of a “violent physical altercation” and “a significant amount of blood” and unspecified weapons.

They added that witnesses allegedly saw Mr Thomas dragging “an object wrapped in a blue-coloured tarp” into the therapist’s car on Saturday, 28 September, the day before Mr Abraham’s body was found.

Police said video surveillance footage also apparently showed Mr Abraham arriving earlier that day at the apartment complex where Mr Thomas lived, wearing the same clothes that his deceased body had been found in.

Police did not specify how Mr Thomas and Mr Abraham knew each other, or if Mr Thomas was a client of the therapist.

Mr Thomas is well-known on the social media app TikTok, where he posts videos for millions of mostly Gen Z followers with commentary on school, relationships and trends.

According to Mr Abraham’s obituary, the victim was a “licensed professional counsellor, motivational speaker, recording artist, author and teacher”. He was also a former Catholic priest who had regular appearances on local television in Baton Rouge, Louisiana.

"""

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/10/03/crude-oil-prices-today.html"
pub_date = "Thu, 03 Oct 2024 17:29:14 GMT"
title = "U.S. crude oil jumps as Biden comments on possible Israel retaliation against Iran"
bib_key = "key-4"
content = '''


U.S. cruderose about 5% on Thursday, on pace for a third consecutive session of gains on fears that Israel could strike Iran's oil industry in retaliation for Tehran's ballisticthis week.

Presidentwas asked by reporters Thursday morning whether the U.S. would support an Israeli strike on. Biden said: "We're discussing that. I think that would be a little – anyway." The president added that "there's nothing going to happen today."

CNBC has reached out to the White House for comment.

Biden's comments were the catalyst that moved prices higher, said Daniel Ghali, senior commodity strategist at TD Securities. "Geopolitical risks in the Middle East are probably at their highest levels since the Gulf War," Ghali told CNBC.

Thehit an intraday high of $73.95 per barrel, a gain of about 5.5%. West Texas Intermediate has gained about 8% this week and is on pace for its best weekly gain since March 2023.

**Here are Thursday's energy prices at around 1 pm ET:**

* November contract: $73.64 per barrel, up $3.54, or 5.05%. Year to date, U.S. crude oil has gained nearly 3%.
* December contract: $77.43 per barrel, up $3.53, or 4.78%. Year to date, the global benchmark is slightly ahead.
* November contract: $2.085 per gallon, up 4.99%. Year to date, gasoline has pulled back about 1%.
* November contract: $2.954 per thousand cubic feet, up 2.36%. Year to date, gas has gained nearly 18%.

The risk of oil supply disruptions increases as fighting in the Middle East intensifies, but OPEC+ is sitting on a large amount of spare crude that could step into the breach, according to Claudio Galimberti, chief economist at Rystad Energy.

"This spare capacity is for now preventing runaway prices amid one of the deepest and most pervasive crises in the Middle East in the past four decades," Galimberti told clients in a Thursday note.

OPEC+ spare capacity would be sufficient to cover a disruption to Iran's exports if Israel strikes the Islamic Republic's oil infrastructure as retaliation for Tehran's ballistic missile attack, said Bjarne Schieldrop, chief commodities analyst at the Swedish bank SEB.

The problem, however, is that the world's spare oil capacity is heavily concentrated in the Middle East, particularly the Gulf states, and could also be at risk if a wider war breaks out, according to Ghali with TD Securities.

If Israel hits Iran's oil industry, traders would begin to worry about supply disruptions in the Strait of Hormuz, Schieldrop said. "That would add a significant risk premium to oil," he told CNBC'sThe strait is one of the most important trade arteries for oil in the world.

As a consequence, oil prices could surge to $200 per barrel if Israel hits Iran's oil infrastructure, Schieldrop said.

## Don't miss these energy insights from CNBC PRO:

* 
* 
* 
* 
* Track all the latest coverage ofat CNBC.com

'''

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/10/03/digital-bank-revolut-slams-meta-over-approach-to-scams.html"
pub_date = "Thu, 03 Oct 2024 16:08:07 GMT"
title = "Digital bank Revolut slams Meta over approach to scams, says tech giant should compensate victims"
bib_key = "key-5"
content = '''


Revolut CEO, Nikolay Storonsky (L) and Meta CEO, Mark Zuckerberg.

Reuters

British financial technology firm Revolut on Thursday criticized Facebook parent company Meta over its approach to tackling fraud, saying the U.S. tech giant should directly compensate people who fall victim to scams via its social media platforms.

A day afterannounced a partnership with U.K. banksand Metro Bank on a data-sharing framework designed to help prevent customers from falling prey to fraud schemes, Revolut said the pact "falls woefully short of what's required to tackle fraud globally."

In a statement, Woody Malouf, Revolut's head of financial crime, said that Meta's plans to tackle financial fraud on its platforms amount to "baby steps, when what the industry really needs is giant leaps forward."

"These platforms share no responsibility in reimbursing victims, and so they have no incentive to do anything about it. A commitment to data sharing, albeit needed, simply isn't good enough," Malouf added.

A Meta spokesperson told CNBC that its intelligence-sharing framework for banks "is designed to enable banks to share information so we can work together to protect people using our respective services."

"Fraud is a multi-sector spanning issue that can only be addressed by working collaboratively," the spokesperson said via email. "We encourage banks including Revolut to join in this effort."

New payment industry reforms will come into force in the U.K. on Oct. 7 that require banks and payment firms to issue victims of so-called authorized push payment (APP) fraud a maximum compensation of £85,000 ($111,000).

Britain's Payments System Regulator had previously recommended a £415,000 maximum compensation amount for fraud victims, but backed down following backlash from banks and payment firms.

Revolut's Malouf said that, while his company is on board with steps the U.K. government is taking to combat fraud, Meta and other social media platforms should do their part to financially compensate those who fall victim to fraud as a result of scams originating on their sites.

The fintech firmalleging that 62% of user-reported fraud on its online banking platform originated from Meta, down from 64% last year.

Facebook was the most common source of all scams reported by Revolut users, accounting for 39% of fraud, while WhatsApp was the second-highest source of such events with an 18% share, the bank said in its "Consumer Security and Financial Crime Report*.*"

'''

[[content]]
section = "News - International"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/sports/2024/10/3/fifa-defers-decision-on-appeal-to-ban-israel-from-football-amid-war-on-gaza?traffic_source=rss"
pub_date = "Thu, 03 Oct 2024 17:05:45 +0000"
title = "FIFA defers decision on appeal to ban Israel from football amid war on Gaza"
bib_key = "key-7"
content = """


*FIFA says its disciplinary committee will ‘review the allegations of discrimination’ raised by Palestine in May.*

FIFA has once again postponed a decision on the Palestinian call to ban Israel from football amid its ongoing war on Gaza.

Following a meeting at its headquarters in Zurich on Thursday, the Federation Internationale de Football Association – FIFA, football’s world governing body – said its disciplinary committee will review the allegations of discrimination that have been raised by the Palestinian Football Association (PFA).

“The FIFA Disciplinary Committee will be mandated to initiate an investigation into the alleged offence of discrimination raised by the Palestine Football Association,” FIFA said in a statement.

“The FIFA Governance, Audit and Compliance Committee will be entrusted with the mission to investigate – and subsequently advise the FIFA Council on – the participation in Israeli competitions of Israeli football teams allegedly based in the territory of Palestine.”

FIFA President Gianni Infantino said the council had implemented “due diligence” on the matter and followed the advice of independent experts.

In May, the PFA presented arguments accusing the Israel Football Association (IFA) of violating FIFA statutes with its war on Gaza and its inclusion of teams located in illegal settlements on Palestinian territory in its domestic league.

The PFA wanted FIFA to adopt “appropriate sanctions” against Israel’s national side and club teams, including an international ban.

The IFA termed the request a “cynical political move”.

FIFA had passed the issue to independent legal advisers who carried out an evaluation and compiled a response.

This is not the first time that FIFA has deferred a ruling. It had promised to address the issue at an extraordinary meeting of its council in July, but deferred the decision until its last council on August 31. It then moved its decision to its October meeting.

Katarina Pijetlovic, head of the PFA’s legal department, termed FIFA’s decision “purely political”.

“FIFA allowed Israel FA to continue using the Palestinian territory [occupied West Bank and East Jerusalem] as their own territory, and to use football under its umbrella as an instrument of colonial expansion,” she wrote in a post on X.

“Will we wait two yrs again, as in 2015-17, for the committee to suggest the obvious and then have their suggestion rejected again?”

> 
> FIFA allowed Israel FA to continue using the Palestinian territory (West Bank & East J.) as their own territory, and to use football under its umbrella as an instrument of colonial expansion. FIFA contributes to human rights abuses & facilitates illegal occupation and colonialism
> 
> — Kat (@katpijetlovic)
> 

Israeli attacks across Gaza since last October have killed more than 41,700 people and wounded over 96,000, according to the Health Ministry in Gaza.

The war has also left its impact on football, the most popular sport in Palestine.

As of August, at least 410 athletes, sports officials or coaches had been killed in the war, according to the PFA. Of these, 297 were footballers, including 84 children.

The war has also forced the Palestinian men’s football team to play its matches away from home.

“The people of Palestine know this team acts as a form of resistance and is conveying a message to the world,” Gaza-based football writer Abubaker Abed told Al Jazeera.

“Football is a stage from where a message can reach millions,” he said, adding that the Palestinians feel let down by the world as Israel continues to destroy sports facilities in the Gaza Strip.

“More than 50 sports facilities have been reduced to rubble in Gaza, including nine out of 10 of Gaza’s stadiums,” said Abed. “Almost every club has been destroyed in this war, while one stadium in Deir el-Balah has been turned into a shelter for thousands of displaced people.”

"""

[[content]]
section = "News - International"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/newsfeed/2024/10/3/biden-discussing-israeli-strikes-on-iran-oil-facilities?traffic_source=rss"
pub_date = "Thu, 03 Oct 2024 16:37:38 +0000"
title = "Biden: Discussing Israeli strikes on Iran oil facilities"
bib_key = "key-8"
content = """
## Biden: Discussing Israeli strikes on Iran oil facilities

US President Joe Biden says his administration is discussing possible Israeli strikes on Iran’s oil facilities. This comes as an Iranian source tells Al Jazeera that Iran sent a message to the US via Qatar that ‘the phase of unilateral self-restraint has ended’ and any Israeli attack would be met with an ‘unconventional response’.

Published On 3 Oct 2024

"""
