[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cn8jg0x5xg8o"
pub_date = "Fri, 20 Sep 2024 14:35:19 GMT"
title = "Israel investigates after its soldiers filmed throwing bodies off roof"
bib_key = "key-5"
content = 'The IDF says the incident does not "conform" to its values, while Palestinian officials say it is a "crime".'

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cjr3255gpjgo"
pub_date = "Thu, 19 Sep 2024 23:12:45 GMT"
title = "Russia’s war dead tops 70,000 as volunteers face 'meat grinder'"
bib_key = "key-6"
content = "More than 70,000 Russian soldiers have died in Ukraine - volunteers now make up the highest number of deaths."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/20/eu-tariffs-on-chinese-evs-are-unlikely-to-dent-their-european-expansion.html"
pub_date = "Fri, 20 Sep 2024 09:48:43 GMT"
title = "Why EU tariffs are unlikely to dent Chinese EV makers' European expansion"
bib_key = "key-8"
content = "To make the European market unattractive for Chinese EV exports, tariffs have to be as high as 50%, according to research group Rhodium."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/20/american-airlines-credit-card-talks-to-pick-citigroup-over-barclays.html"
pub_date = "Fri, 20 Sep 2024 13:15:26 GMT"
title = "American Airlines in talks to pick Citigroup over rival bank Barclays for crucial credit card deal, sources say"
bib_key = "key-9"
content = "American has been working with banks and card networks on a new deal with the aim of consolidating its business with a single issuer, sources tell CNBC."

[[content]]
section = "Personal"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/newsfeed/2024/9/20/israeli-airstrikes-hit-densely-populated-beirut-neighbourhood?traffic_source=rss"
pub_date = "Fri, 20 Sep 2024 13:49:30 +0000"
title = "Israeli airstrikes hit densely populated Beirut neighbourhood"
bib_key = "key-11"
content = "Israeli airstrikes have hit the densely populated Dahiyeh neighbourhood of Lebanon’s capital Beirut."

[[content]]
section = "Personal"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/9/20/dozens-of-women-accuse-former-harrods-boss-mohamed-al-fayed-of-sexual-abuse?traffic_source=rss"
pub_date = "Fri, 20 Sep 2024 13:38:45 +0000"
title = "Dozens of women accuse former Harrods boss Mohamed al-Fayed of sexual abuse"
bib_key = "key-12"
content = "Harrods, now under Qatari ownership, issues apology for abuse of power when store was under al-Fayed’s control."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/17/world/middleeast/israel-hezbollah-lebanon-war-impact.html"
pub_date = "Wed, 18 Sep 2024 08:54:56 +0000"
title = "A Look at Israel-Hezbollah Tensions and How a Wider War Could Impact Lebanon"
bib_key = "key-14"
content = "Hezbollah and Israel have repeatedly traded strikes since the Gaza war began in October, killing civilians and combatants in Lebanon and Israel."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/podcasts/harris-trump-spending-hezbollah.html"
pub_date = "Fri, 20 Sep 2024 10:00:14 +0000"
title = "Harris Outspends Trump in Ad Battle, and Israel Bombards Hezbollah"
bib_key = "key-15"
content = "Plus, an iconic kitchen brand files for bankruptcy."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/20/us/politics/kamala-harris-trump-campaign-spending.html"
pub_date = "Fri, 20 Sep 2024 14:14:12 +0000"
title = "Kamala Harris Outspends Donald Trump by Tens of Millions Online"
bib_key = "key-16"
content = "The week of their debate, Kamala Harris outspent Donald Trump by 20 to 1 on Facebook and Instagram. It was just one sign of how uneven their online advertising battle has become."

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/localnews/2024/09/20/man-fatally-shot-by-officers-years-after-police-tried-to-steer-him-away-from-crime/"
pub_date = "Fri, 20 Sep 2024 15:02:35 +0000"
title = "Man fatally shot by officers years after police tried to steer him away from crime"
bib_key = "key-18"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2022/06/polic-blotter-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2022/06/polic-blotter-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />ASSOCIATED PRESS WEST HAVEN — Connecticut police officers fatally shot a 36-year-old man whom authorities had tried to steer away from crime years ago. A state police sergeant and two New Haven police officers opened fire on the man late Thursday afternoon at a car wash in West Haven after they say he displayed a [&#8230;]'

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/localnews/2024/09/20/torrington-schools-closed-because-of-threat/"
pub_date = "Fri, 20 Sep 2024 14:19:25 +0000"
title = "Torrington schools closed because of online threat; Waterbury increases police presence"
bib_key = "key-19"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/08/20240802-131400-pic-598577038-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" loading="lazy" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/08/20240802-131400-pic-598577038-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />BY SLOAN BREWSTER AND Livi Stanford &#124; REPUBLICAN-AMERICAN TORRINGTON — Schools in Torrington and Bristol were closed Friday due to online threats. In a message to the community, Superintendent Michael Wilson said school officials were “made aware of a very disturbing and threatening post on social media.” He said they had contacted Torrington police, which [&#8230;]'
