[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cew2x50808go"
pub_date = "Wed, 30 Oct 2024 14:29:02 GMT"
title = "'I'm not a one-issue voter, but this is huge': Women on how abortion shaped their vote"
bib_key = "key-1"
content = """


## 'I'm not a one-issue voter, but this is huge': Women on how abortion shaped their vote

BBC

The 2024 presidential election is the first since the Supreme Court overturned Roe v Wade, which protected the national right to an abortion.

The gender divide has been prominent in this election, with polls suggesting Kamala Harris has an advantage among women and former President Donald Trump is enjoying a similar lead among men.

The BBC has been speaking to women voters about how they are considering gender and abortion as they cast their ballots in the final days of the campaign.

I'm concerned about women's rights and women's health care. I'm not a one-issue voter, but that is a huge one. I work in the medical sector and I was very personally affected by the overturn of Roe v Wade because I wasn't able to get access to a lot of the drugs I needed. Nobody was sure of what the legality was... even though they're used for other things.

The whole Republican stance is smaller government and don't let government make my personal decisions, so why are they trying to legislate what a woman can do with her body?

[A Harris presidency] would mean that all the things that my parents told me when I was younger were true - that just because you're a girl doesn't mean that you are limited.

[Trump] has definitely said things that he probably should have unsaid. I would have to shake my finger at that, especially as a woman, but I have yet to hear anything that would make me change my mind about my vote.

I'm not voting personality. I'm voting policy. I don't have to marry the man. I don't have to deal with him. I have to deal with his policies.

On abortion, [Harris] is not giving a gestational parameter of how late somebody can get an abortion. That cannot be-open ended. I was a NICU [neonatal intensive care unit] nurse for 17 years... I care about women's rights. I care about women. The mother is the first patient. However, that is the turn-off to me that she won't give an answer to that.

* 
* 
* 

I am definitely concerned about the direction that reproductive rights are going in parts of the country. I feel that Trump's attempts to communicate that he understands why [reproductive rights] is an important issue to women has fallen woefully short.

I think Harris has an innate understanding of its importance, just being a woman and a woman of colour. Would I like her to lay out her plans a little bit more to potentially expand reproductive rights? Absolutely. But Trump has set the bar so low that she could really continue to not even mention it and she would still be doing a better job.

[A Harris presidency] brings tears to my eyes just to think about. I have a nine-year-old daughter and she's old enough to start having aspirations and to start paying attention to the world around her.

This ain't my first rodeo and I've gotten to the point in my life where I can look past the advertising they're doing for two specific groups.

It's wonderful that we have Harris as a female seriously running for the presidency and that she has been a vice-president and has some experience. But Trump, when he was in office, I wasn't too upset with what he was doing.

I wouldn't mind having a female president but some of Harris's political doctrine and what I think is right don't line up.

I really would love this to be a moment of celebration as we elect a woman of colour to our highest office, but unfortunately with how tight the election is against Trump and how disappointing [Harris's] campaign has been on some of the issues that matter to me, it's been hard to be as celebratory as I'd like.

Obviously abortion is a huge issue that needs to be addressed, but I'm not necessarily happy, I should say, with either candidate's approaches in addressing the issue.

I understand Harris has a policy where she wants to codify Roe v Wade, but I think women's rights and issues extend outside of just abortion access. Trump is very wishy-washy on the issue of women's rights, so it's hard to pin him down on any stance.

.

I think [Trump] is really the only possibility because I think Harris is just clueless and incompetent. I think she would be a disaster for this country, just listening to her mumble and evade. I just get a horrible feeling about her.

I am pro-choice, actually, within reason. Not a late-term abortion. I don't agree with that. But I think Trump by really relegating [legislation] to the states themselves, he's being sensible.

Harris doesn't have much to run on so that's her big selling point with women. She doesn't have much substance to her, in other words, so she just hammers on and on about the abortion issue.

Reproductive rights for women are huge for me as a woman, especially living in the state of Florida where there is an amendment on the ballot that will guarantee the protection for abortion rights.

I really want to support a party that's going to support reproductive rights for women and not just women, but for everybody, because what's to say it's not going to spread elsewhere? It starts with women, usually, but it goes on and on.

Our government is at least 50 years behind the times for a lot of things - especially other countries throughout the world having better representation. I have a niece that I love dearly. The fact that she could see [a female president], and just for that to be a normal thing for her, will be huge.

I was actually going to vote for Harris, but then she started doubling down on how abortion is reproductive health... I'm a Catholic. I am pro-life.

The problem that I ran into is that I don't know how any Catholic can vote for somebody who spews the stuff like what we saw [from Trump] at Madison Square Garden recently. I take the injunction to welcome the stranger and to feed and clothe very seriously.

So under those circumstances, I've got nobody I can vote for.

I get so scared. We actually can't go back. It's very frightening to me. I had more rights than my granddaughter is going to have in her future and that's not right.

It is so disturbing that it is so close. [Trump] is a felon out on bail. I don't understand the Republicans. They used to be the law and order [party], supposedly, and it's now this.

I think a lot [of women] are coming out and saying, 'Why are you telling us what to do with our bodies?' Abortion is a personal thing and it's up to the doctor and the woman. It is none of my business.

* SIMPLE GUIDE:
* EXPLAINER:
* ANALYSIS:
* ON THE GROUND:
* POLLS:
* PODCAST:

"""
