[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c79n1v4d203o"
pub_date = "Thu, 19 Sep 2024 19:44:31 GMT"
title = "Hezbollah leader says exploding device attacks crossed 'all red lines'"
bib_key = "harry"
content = 'Hassan Nasrallah calls the killing of 37 people by exploding pagers and radios an "unprecedented blow".'

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c04p7q3k4k9o"
pub_date = "Thu, 19 Sep 2024 19:12:31 GMT"
title = "Surgeon 'became robotic' to treat sheer volume of wounded Lebanese"
bib_key = "harry"
content = "Elias Jaradeh worked for almost 24 hours on the wounded, many of whom lost eyes or the use of their hands."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/19/nike-ceo-john-donahoe-is-out-replaced-by-elliott-hill.html"
pub_date = "Thu, 19 Sep 2024 22:23:35 GMT"
title = "Nike CEO John Donahoe is out, replaced by company veteran Elliott Hill"
bib_key = "harry"
content = "Nike CEO John Donahoe will retire from the company in October. He will be replaced by company veteran Elliott Hill."

[[content]]
section = "News"
source = "CNBC International is the world leader for news on business, technology, China, trade, oil prices, the Middle East and markets."
link = "https://www.cnbc.com/2024/09/19/the-fed-has-set-out-on-a-recalibration-of-policy-heres-what-powells-new-buzzword-means.html"
pub_date = "Thu, 19 Sep 2024 19:29:47 GMT"
title = "The Fed has set out on a 'recalibration' of policy. Here's what Powell's new buzzword means"
bib_key = "harry"
content = "Asset prices soared as investors took Powell at his word that the outsized rate cut wasn't in response to a substantial economic weakening."

[[content]]
section = "News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/9/19/israel-intensifies-air-raids-on-southern-lebanon-amid-escalation-fears?traffic_source=rss"
pub_date = "Thu, 19 Sep 2024 20:53:50 +0000"
title = "Israel intensifies air raids on southern Lebanon amid escalation fears"
bib_key = "harry"
content = "Israeli defence minister says Hezbollah to &#039;pay an increasing price&#039; as group promises retaliation over device attacks."

[[content]]
section = "News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/program/newsfeed/2024/9/19/video-captures-israeli-soldiers-pushing-dead-bodies-from-roof?traffic_source=rss"
pub_date = "Thu, 19 Sep 2024 19:22:24 +0000"
title = "Video captures Israeli soldiers pushing dead bodies from roof"
bib_key = "harry"
content = "Video from the occupied West Bank town of Qabatiya shows Israeli soldiers pushing dead bodies off a roof."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/19/world/middleeast/israel-lebanon-hezbollah-strikes.html"
pub_date = "Thu, 19 Sep 2024 22:26:50 +0000"
title = "Israel Strikes Hezbollah as Nasrallah Vows Retribution"
bib_key = "harry"
content = "The Hezbollah leader, Hassan Nasrallah, did not say how his group would respond to attacks on hand-held devices, which killed dozens when pagers and walkie-talkies exploded."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/19/us/politics/israel-hezbollah-pager-attacks.html"
pub_date = "Thu, 19 Sep 2024 16:28:46 +0000"
title = "A New Era in Sabotage: Turning Ordinary Devices Into Grenades, on a Mass Scale"
bib_key = "harry"
content = "The attacks in Lebanon required getting deep into the supply chain, which is difficult to do. But the sabotage contributes to a sense of vulnerability that ordinary devices can become a source of danger."

[[content]]
section = "News"
source = ""
link = "https://www.nytimes.com/2024/09/19/us/politics/mark-robinson-cnn-report-presidential-race.html"
pub_date = "Thu, 19 Sep 2024 22:14:12 +0000"
title = "How the Robinson Report Could Affect the Presidential Race in North Carolina"
bib_key = "harry"
content = "A Democratic presidential candidate has not won North Carolina since 2008. But the drama around Lt. Gov. Mark Robinson, the Republican nominee for governor, is sure to bolster their hopes."

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/today_in_history/2024/09/19/today-in-history-september-20-2/"
pub_date = "Thu, 19 Sep 2024 23:05:50 +0000"
title = "Today in History: September 20"
bib_key = "harry"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2022/06/Today-In-History-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2022/06/Today-In-History-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />Today in History: September 20, Billie Jean King wins &#8220;Battle of the Sexes&#8221; By The Associated Press undefined Today is Friday, Sept. 20, the 264th day of 2024. There are 102 days left in the year. Today in history: On Sept. 20, 1973, in their so-called &#8220;Battle of the Sexes,&#8221; tennis star Billie Jean King [&#8230;]'

[[content]]
section = "News - Local"
source = "Northwest Connecticut's news and information leader"
link = "https://www.rep-am.com/obituaries/2024/09/19/jeremiah-t-fallon-jr/"
pub_date = "Thu, 19 Sep 2024 20:57:23 +0000"
title = "Jeremiah T. Fallon Jr.,"
bib_key = "harry"
content = '<img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/09/20240919-175723-pic-404980089-150x150.jpg" class="webfeedsFeaturedVisual wp-post-image" alt="" decoding="async" style="float: right; margin-left: 5px;" link_thumbnail="" loading="lazy" /><img width="150" height="150" src="https://cdn.rep-am.com/wp-content/uploads/2024/09/20240919-175723-pic-404980089-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="float:left; margin:0 15px 15px 0;" />NORTH CANAAN &#8211; Jeremiah Thomas Fallon Jr., 93, passed away peacefully on Sept. 16, 2024, at Noble Horizons. He was the loving husband of the late Anne Perotti Fallon. Jerry was born on March 26, 1931 in Great Barrington, Mass., to the late Jeremiah Thomas Fallon Sr. and Roberta Fitzgerald Fallon. He is survived by [&#8230;]'
