[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c80rkv0k4j8o"
pub_date = "Thu, 26 Sep 2024 12:13:25 GMT"
title = "Escalating Trump row looms over Zelensky's US visit"
bib_key = "key-1"
content = '''


The Speaker of the US House Mike Johnson has demanded that Ukraine fire its ambassador to Washington, as a feud between the Republican Party and Volodymyr Zelensky escalates.

Johnson's intervention comes after President Zelensky visited an arms factory in Scranton, Pennsylvania - the hometown of President Joe Biden in a key swing state - with several top Democrats.

In a public letter, the top Republican said the visit was "designed to help Democrats" and claimed it amounted to "election interference".

The row has threatened to overshadow Zelensky's meeting with President Joe Biden on Thursday, during which he will present a "plan for victory" in his country's war with Russia.

Since his arrival to the US on Sunday, Zelensky has ramped up efforts to persuade the US and other allies to lend more support to Ukraine as it fends off Russian advances.

On Thursday, Biden announced that the US will send $7.9bn (£5.9bn) worth of military aid to Ukraine in a surge of assistance as his presidency nears its end.

The aid, part of a $61bn package that passed Congress in April, includes additional Patriot air defence missiles and long-range munitions.

The weapons package will be approved through presidential drawdown authority and will pull from existing Pentagon supplies to deliver the arms more quickly.

Congressional Republicans blocked the Biden administration's $61bn military package for months earlier this year, before ultimately relenting and passing the legislation in April. Before that, arms supplies to Ukraine had dried up for several months.

The US has been the largest foreign donor to Ukraine, with $56bn provided for its defence to date.

Responding to the aid package, Zelensky thanked the US and said he was "grateful to Joe Biden, US Congress and its both parties".

The Ukrainian president said the assistance would be used "in the most efficient and transparent manner" to achieve "victory for Ukraine, just and lasting peace, and transatlantic security".

Russia's missile and drone attacks on Ukraine have continued while Zelensky is in the US.

The Sumy, Odesa and Kyiv regions were all attacked overnight, leaving one woman dead in Odesa and numerous reported injuries.

In the capital, air raid sirens and explosions from Ukraine's air defences continued for hours.

"I woke up to the sound of the Shahed drone. I got up and saw the reflection in the windows, how a big ball of fire was falling down," said Maryna, a 31-year-old mother of two children.

Zelensky had planned to present his priorities outlined in Thursday's statement to the two presidential candidates: Kamala Harris and Donald Trump.

However, an official on Donald Trump's campaign said the Republican nominee would not meet the Ukrainian leader on his tour of the US this week.

Trump and Zelensky have long held a fractious relationship. In 2019, Trump was impeached by the US House over accusations that he pressured Ukraine's leader to dig up damaging information on a political rival.

He has frequently echoed Russian talking points over the war. At a campaign event on Wednesday he mocked Zelensky as the "greatest salesman on Earth" and accused the Ukrainian leader of refusing to "make a deal" with Moscow.

During an earlier rally on Tuesday, Trump also praised Russia's military capabilities, saying: "They beat Hitler, they beat Napoleon - that’s what they do, they fight."

The former president's remarks come amid a growing row between Zelensky and the Republican party over his visit to an ammunition factory in Biden's hometown of Scranton in the key swing state of Pennsylvania.

During the visit, Zelensky appeared with Pennsylvania Governor Josh Shapiro and several other top Democrats. Speaker Johnson accused the president of taking part in a "partisan campaign event" designed to help Vice-President Kamala Harris' camapign.

Meanwhile, the Republican-led House Oversight Committee had already announced that it would investigate whether Zelensky's trip was an attempt to use a foreign leader to benefit Vice-President Kamala Harris' campaign.

Congressional Republicans blocked the Biden administration's $61bn military package for months earlier this year, before ultimately relenting and passing the legislation in April.

Before that, arms supplies to Ukraine had dried up for several months.

* SIMPLE GUIDE:
* EXPLAINER:
* FACT CHECK:

North America correspondent Anthony Zurcher makes sense of the race for the White House in his weekly US Election Unspun newsletter.

Readers in the UK. Those outside the UK

'''

[[content]]
section = "News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/cgeyg2g288wo"
pub_date = "Thu, 26 Sep 2024 11:27:03 GMT"
title = "Sudan army launches major attack on capital Khartoum"
bib_key = "key-2"
content = '''


Reuters

Smoke was seen rising over Khartoum on Thursday during the fighting

Sudan's army has launched a major offensive against the powerful paramilitary group it is fighting in the country's civil war, targeting areas in the capital it lost at the start of the conflict.

In dawn strikes on Thursday, government forces shelled Rapid Support Forces (RSF) bases in the capital Khartoum, and Bahri to its north.

Sudan has been embroiled in a war since the army and the RSF began a vicious struggle for power in April 2023, leading to what the UN has called one of the world's worst humanitarian crises.

Up to 150,000 people have been killed in the conflict while more than 10 million people - about a fifth of the population - have been forced from their homes.

Witnesses reported intense aerial bombardments and heavy fighting on Thursday as army troops crossed two key bridges over the River Nile - which had separated government-controlled areas in Omdurman from the regions controlled by the RSF.

Since early in the war, the paramilitaries have been in control of nearly all of the capital.

Thursday's advances appear to be the government's first significant push in months to regain some territory.

* 
* 
* 

The offensive comes just before army chief General Abdel Fattah al-Burhan is set to address the UN General Assembly in New York later on Thursday.

The UN has called for "immediate" action to protect civilians and end the fighting.

Much of the worst and most intense fighting has taken place in heavily populated regions. Both sides have accused each other of indiscriminately bombing civilian areas.

"Relentless hostilities across the country have brought misery to millions of civilians, triggering the world’s fastest-growing displacement crisis,"

It noted that half of the 10 million people who had fled their homes were children, while at least two million have sought protection in neighbouring countries.

It also called Sudan "the world's largest hunger crisis". There are fears of widespread famine as people have not been able to grow any crops.

There have also been warnings of a possible genocide against non-Arabs in the western region of Darfur.

A cholera epidemic is also raging throughout the country- more than 430 people have died from the easily-treatable disease in the past month, the health ministry said on Wednesday.

But getting treatment to those affected areas is hugely complicated by the conflict.

## More about Sudan's civil war from the BBC:

* 
* 
*'''
