[[content]]
section = "World News"
source = "Breaking News, World News and Video from Al Jazeera"
link = "https://www.aljazeera.com/news/2024/11/1/jailed-algerian-journalist-ihsane-el-kadi-freed-after-presidential-pardon?traffic_source=rss"
pub_date = "Fri, 01 Nov 2024 13:19:03 +0000"
title = "Jailed Algerian journalist Ihsane El Kadi freed after presidential pardon"
bib_key = "key-1"
content = """


*President Abdelmadjid Tebboune pardons 4,000 detainees to mark 70th anniversary of the independence war with France.*

Prominent Algerian journalist Ihsane El Kadi has been freed by a presidential pardon, his lawyers say, after being imprisoned for taking foreign funding for his media outlets and “threatening state security”.

El Kadi, 65, was released on Friday after President Abdelmadjid Tebboune signed two decrees pardoning more than 4,000 detainees to mark the anniversary of the 1956-1962 conflict with France that led to the North African country’s independence.

His lawyer Noureddine Ahmine posted on Facebook: “What joy! Ihsane El Kadi is free!” alongside a picture of the journalist at home with his family.

Another lawyer, Nabila Smail, posted: “At last Ihsane El Kadi is back home with his loved ones. Freed on November 1. The end of a nightmare.”

El Kadi, who heads Interface Medias, which includes the Maghreb Emergent news website and Radio M, had served a year and four months of the seven-year sentence he received in June 2023.

Seven years is the maximum penalty under an article in the penal code that criminalises anyone who receives “funds, a grant or otherwise … to carry out acts capable of undermining state security”.

He was first arrested in December 2022 and held.

In addition to his imprisonment, the court ordered the two media entities dissolved and ruled the two companies and El Kadi pay a total of 11.7 million dinars ($86,200) in fines.

The two media projects were key outlets during the Hirak protest movement, which led to the resignation of octogenarian Presidentin 2019 after 20 years in power.

Among the Hirak movement prisoners freed was Mohamed Tadjadit, 29, dubbed the “poet of the Hirak” for his recitations during the mass protests and for his posts on Facebook.

El Kadi was sentenced to seven years after he appealed an initial five-year term for “foreign financing of his business”.

His lawyers had argued that the funds had been sent by his London-based daughter Tin Hinane, a shareholder in his media group, to settle debts.

El Kadi’s arrest sparked a wave of solidarity among his colleagues and rights activists in both Algeria and Europe.

A petition by Reporters Without Borders, known by its French initials RSF, a media rights watchdog, attracted more than 10,000 signatures.

RSF on Friday expressed “immense relief” at El Kadi’s release, saying it hoped this would “also signal a lifting of restrictions on press freedom”.

Algeria ranks 139 of 180 countries and territories on RSF’s 2024 World Press Freedom Index.

"""

[[content]]
section = "World News"
source = "BBC News - World"
link = "https://www.bbc.com/news/articles/c62lkne32v9o"
pub_date = "Fri, 01 Nov 2024 12:14:51 GMT"
title = "Trapped in cars and garages: Why Valencia floods proved so deadly"
bib_key = "key-3"
content = """


Reuters

Firefighters pump the water out of a tunnel where vehicles piled up in Alfafar, Valencia

As Spain reels from the flash floods which struck the south-east of the country this week, many are wondering why the death toll, which currently stands at over 200, is so high.

Almost all of the deaths confirmed so far have been in the Valencia region on the Mediterranean coast.

Some areas have been particularly devastated: the town of Paiporta, population 25,000, reported at least 62 deaths.

Various factors, including drivers becoming trapped in their cars, poor planning by officials and extreme rainfall being exacerbated by climate change are all likely to have contributed.

The civil protection agency, overseen by the regional government, issued an emergency alert to the phones of people in and around the city of Valencia after 20:00 local time (19:00 GMT) on Tuesday, by which time the flood water was swiftly rising in many areas and in some cases already wreaking havoc.

A large number of those killed were on the roads, in many cases returning from work, when the flash floods struck.

Video footage shows how a first wave of flood water washed through Paiporta as cars were still circulating. Although rainfall was heavier in other areas, such as Utiel and Chiva, Paiporta’s geography, with a ravine running through its centre, made the impact of the flood particularly devastating.

Mayor Maribel Albalat said that the town was ill-prepared in terms of planning, with many ground-floor flats. Six residents of an elderly care home died when the flood water washed into the building when they were still on the ground floor. She also suggested there was an element of complacency.

“In Paiporta we don’t tend to have floods and people aren’t afraid,” she said.

* 

* 

* 

Garages were a particular death trap.

“When it rains people normally go down to their garages to get their cars out in case their garage is flooded,” Ms Albalat said.

That appears to have been the case in the neighbourhood of La Torre, on the outskirts of Valencia, where the bodies of seven people were recovered from the garage of a residential building.

The A3 motorway connecting Valencia to Madrid was one of many roads where motorists were trapped as the water level rose, leaving them unsure whether it was safer to stay in the vehicle or not.

“There are almost certainly more people who have died because the water washed people away who had got out of their cars,” one survivor told the Telecinco TV channel. Another survivor said the water had been up to his chest.

An eye-witness described seeing one driver who had got out of his car who had strapped himself to a lamppost with his belt, to stop himself from being washed away. It is unknown whether he survived.

The mayor of Chiva, Amparo Fort, warned on Thursday that nearby there were still “hundreds of cars turned upside down and they will surely have people inside them”.

On Thursday morning, the Guardia Civil shared advice on how to escape from a car during a flood. People caught in floods are advised to try and escape though their cars' windows and windscreen.

Other factors also appear to help explain why Valencia was so devastated by the weather event.

Much of the area most heavily affected, in and surrounding the country’s third-largest city, is densely populated.

A lack of rainfall throughout the rest of the year has left the ground in many areas of eastern and southern Spain unable to absorb rainwater efficiently.

Pablo Aznar, a researcher at the Socio-Economic Observatory of Floods and Droughts (Obsis), warned that much of the area affected had undergone what he described as “untrammelled development”, with many areas covered in impermeable materials, which “increases the danger posed by these events”.

The warming climate is also likely to have contributed to the severity of the floods.

In a preliminary report, World Weather Attribution (WWA), a group of international scientists who investigate global warming’s role in extreme weather, found that the rainfall which struck Spain was 12% heavier due to climate change and that the weather event experienced is twice as likely.

"""
