version: "2.4"
services:
  
  #feedpress
  feedpress:
    image: sullivant/feedpress:latest
    restart: "no"
    ports:
      - 8081:8081
    volumes:
      - ./assets:/assets
      - ./data:/data
      - ./input:/input
      - ./output:/output
      - ./templates:/templates
