version: "2.4"
services:
  
  #feedpress
  feedpress:
    image: sullivant/feedpress:latest
    restart: "no"
    ports:
      - 8081:8081
## if desired, volumes can be created to redirect the output directory, etc.
#   volumes:
#     - ./output:/output
