refresh_rate: 30 seconds
appenders:
  stdout:
    kind: rolling_file
    path: "../log/feedpress.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - [{T}] - {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 500kb
      roller:
        kind: delete      
root:
  level: info
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - stdout
    additive: false
